# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/actor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/actor.proto\x12\x07gz.msgs\x1a\x14gz/msgs/entity.proto\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/pose.proto\"\xcc\x04\n\x05\x41\x63tor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1f\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12\x1b\n\x04pose\x18\x03 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x15\n\rskin_filename\x18\x04 \x01(\t\x12\x12\n\nskin_scale\x18\x05 \x01(\x02\x12,\n\nanimations\x18\x06 \x03(\x0b\x32\x18.gz.msgs.Actor.Animation\x12\x13\n\x0bscript_loop\x18\x07 \x01(\x08\x12\x1a\n\x12script_delay_start\x18\x08 \x01(\x02\x12\x19\n\x11script_auto_start\x18\t \x01(\x08\x12/\n\x0ctrajectories\x18\n \x03(\x0b\x32\x19.gz.msgs.Actor.Trajectory\x12\x1f\n\x06parent\x18\x0b \x01(\x0b\x32\x0f.gz.msgs.Entity\x1aQ\n\tAnimation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\r\n\x05scale\x18\x03 \x01(\x02\x12\x15\n\rinterpolate_x\x18\x04 \x01(\x08\x1a\x35\n\x08Waypoint\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\x1b\n\x04pose\x18\x02 \x01(\x0b\x32\r.gz.msgs.Pose\x1a\x63\n\nTrajectory\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07tension\x18\x03 \x01(\x02\x12*\n\twaypoints\x18\x04 \x03(\x0b\x32\x17.gz.msgs.Actor.WaypointB\x1a\n\x0b\x63om.gz.msgsB\x0b\x41\x63torProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013ActorProtos'
  _globals['_ACTOR']._serialized_start=97
  _globals['_ACTOR']._serialized_end=685
  _globals['_ACTOR_ANIMATION']._serialized_start=448
  _globals['_ACTOR_ANIMATION']._serialized_end=529
  _globals['_ACTOR_WAYPOINT']._serialized_start=531
  _globals['_ACTOR_WAYPOINT']._serialized_end=584
  _globals['_ACTOR_TRAJECTORY']._serialized_start=586
  _globals['_ACTOR_TRAJECTORY']._serialized_end=685
# @@protoc_insertion_point(module_scope)
