# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/annotated_oriented_3d_box.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/annotated_oriented_3d_box.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import oriented_3d_box_pb2 as gz_dot_msgs_dot_oriented__3d__box__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'gz/msgs/annotated_oriented_3d_box.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x1dgz/msgs/oriented_3d_box.proto\"m\n\x16\x41nnotatedOriented3DBox\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12#\n\x03\x62ox\x18\x02 \x01(\x0b\x32\x16.gz.msgs.Oriented3DBox\x12\r\n\x05label\x18\x03 \x01(\rB+\n\x0b\x63om.gz.msgsB\x1c\x41nnotatedOriented3DBoxProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.annotated_oriented_3d_box_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\034AnnotatedOriented3DBoxProtos'
  _globals['_ANNOTATEDORIENTED3DBOX']._serialized_start=105
  _globals['_ANNOTATEDORIENTED3DBOX']._serialized_end=214
# @@protoc_insertion_point(module_scope)
