# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/annotated_axis_aligned_2d_box_v.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/annotated_axis_aligned_2d_box_v.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import annotated_axis_aligned_2d_box_pb2 as gz_dot_msgs_dot_annotated__axis__aligned__2d__box__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-gz/msgs/annotated_axis_aligned_2d_box_v.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a+gz/msgs/annotated_axis_aligned_2d_box.proto\"y\n\x1b\x41nnotatedAxisAligned2DBox_V\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x39\n\rannotated_box\x18\x02 \x03(\x0b\x32\".gz.msgs.AnnotatedAxisAligned2DBoxB0\n\x0b\x63om.gz.msgsB!AnnotatedAxisAligned2DBox_VProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.annotated_axis_aligned_2d_box_v_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB!AnnotatedAxisAligned2DBox_VProtos'
  _globals['_ANNOTATEDAXISALIGNED2DBOX_V']._serialized_start=125
  _globals['_ANNOTATEDAXISALIGNED2DBOX_V']._serialized_end=246
# @@protoc_insertion_point(module_scope)
