# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/any.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/any.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import quaternion_pb2 as gz_dot_msgs_dot_quaternion__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/any.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x13gz/msgs/color.proto\x1a\x12gz/msgs/pose.proto\x1a\x18gz/msgs/quaternion.proto\x1a\x12gz/msgs/time.proto\x1a\x16gz/msgs/vector3d.proto\"\x89\x04\n\x03\x41ny\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.gz.msgs.Any.ValueType\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x04 \x01(\x05H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x06 \x01(\x08H\x00\x12+\n\x0evector3d_value\x18\x07 \x01(\x0b\x32\x11.gz.msgs.Vector3dH\x00\x12%\n\x0b\x63olor_value\x18\x08 \x01(\x0b\x32\x0e.gz.msgs.ColorH\x00\x12%\n\x0cpose3d_value\x18\t \x01(\x0b\x32\r.gz.msgs.PoseH\x00\x12/\n\x10quaternion_value\x18\n \x01(\x0b\x32\x13.gz.msgs.QuaternionH\x00\x12#\n\ntime_value\x18\x0b \x01(\x0b\x32\r.gz.msgs.TimeH\x00\"\x85\x01\n\tValueType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x44OUBLE\x10\x01\x12\t\n\x05INT32\x10\x02\x12\n\n\x06STRING\x10\x03\x12\x0b\n\x07\x42OOLEAN\x10\x04\x12\x0c\n\x08VECTOR3D\x10\x05\x12\t\n\x05\x43OLOR\x10\x06\x12\n\n\x06POSE3D\x10\x07\x12\x0f\n\x0bQUATERNIOND\x10\x08\x12\x08\n\x04TIME\x10\tB\x07\n\x05valueB\x1a\n\x0b\x63om.gz.msgsB\x0b\x45mptyProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.any_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013EmptyProtos'
  _globals['_ANY']._serialized_start=164
  _globals['_ANY']._serialized_end=685
  _globals['_ANY_VALUETYPE']._serialized_start=543
  _globals['_ANY_VALUETYPE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
