# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/atmosphere.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/atmosphere.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/atmosphere.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xc4\x01\n\nAtmosphere\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.gz.msgs.Atmosphere.Type\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x10\n\x08pressure\x18\x04 \x01(\x01\x12\x14\n\x0cmass_density\x18\x05 \x01(\x01\x12\x19\n\x11\x65nable_atmosphere\x18\x06 \x01(\x08\"\x15\n\x04Type\x12\r\n\tADIABATIC\x10\x00\x42\x1f\n\x0b\x63om.gz.msgsB\x10\x41tmosphereProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.atmosphere_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\020AtmosphereProtos'
  _globals['_ATMOSPHERE']._serialized_start=60
  _globals['_ATMOSPHERE']._serialized_end=256
  _globals['_ATMOSPHERE_TYPE']._serialized_start=235
  _globals['_ATMOSPHERE_TYPE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
