# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/axis_aligned_box.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/axis_aligned_box.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egz/msgs/axis_aligned_box.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/vector3d.proto\"\x7f\n\x0e\x41xisAlignedBox\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12%\n\nmin_corner\x18\x02 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12%\n\nmax_corner\x18\x03 \x01(\x0b\x32\x11.gz.msgs.Vector3dB#\n\x0b\x63om.gz.msgsB\x14\x41xisAlignedBoxProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.axis_aligned_box_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\024AxisAlignedBoxProtos'
  _globals['_AXISALIGNEDBOX']._serialized_start=89
  _globals['_AXISALIGNEDBOX']._serialized_end=216
# @@protoc_insertion_point(module_scope)
