# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/axis.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/axis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gz/msgs/axis.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xa5\x02\n\x04\x41xis\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1e\n\x03xyz\x18\x02 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x13\n\x0blimit_lower\x18\x03 \x01(\x01\x12\x13\n\x0blimit_upper\x18\x04 \x01(\x01\x12\x14\n\x0climit_effort\x18\x05 \x01(\x01\x12\x16\n\x0elimit_velocity\x18\x06 \x01(\x01\x12\x0f\n\x07\x64\x61mping\x18\x07 \x01(\x01\x12\x10\n\x08\x66riction\x18\x08 \x01(\x01\x12\x10\n\x08position\x18\n \x01(\x01\x12\x10\n\x08velocity\x18\x0b \x01(\x01\x12\r\n\x05\x66orce\x18\x0c \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\r \x01(\x01\x12\x18\n\x10xyz_expressed_in\x18\x0e \x01(\tB\x19\n\x0b\x63om.gz.msgsB\nAxisProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.axis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\nAxisProtos'
  _globals['_AXIS']._serialized_start=78
  _globals['_AXIS']._serialized_end=371
# @@protoc_insertion_point(module_scope)
