# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/battery_state.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/battery_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/battery_state.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xaa\x02\n\x0c\x42\x61tteryState\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0f\n\x07voltage\x18\x02 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x03 \x01(\x01\x12\x0e\n\x06\x63harge\x18\x04 \x01(\x01\x12\x10\n\x08\x63\x61pacity\x18\x05 \x01(\x01\x12\x12\n\npercentage\x18\x06 \x01(\x01\x12\x44\n\x13power_supply_status\x18\x07 \x01(\x0e\x32\'.gz.msgs.BatteryState.PowerSupplyStatus\"[\n\x11PowerSupplyStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x43HARGING\x10\x01\x12\x0f\n\x0b\x44ISCHARGING\x10\x02\x12\x10\n\x0cNOT_CHARGING\x10\x03\x12\x08\n\x04\x46ULL\x10\x04\x42!\n\x0b\x63om.gz.msgsB\x12\x42\x61tteryStateProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.battery_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022BatteryStateProtos'
  _globals['_BATTERYSTATE']._serialized_start=63
  _globals['_BATTERYSTATE']._serialized_end=361
  _globals['_BATTERYSTATE_POWERSUPPLYSTATUS']._serialized_start=270
  _globals['_BATTERYSTATE_POWERSUPPLYSTATUS']._serialized_end=361
# @@protoc_insertion_point(module_scope)
