# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/camera_lens.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/camera_lens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gz/msgs/camera_lens.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xcc\x01\n\nCameraLens\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02\x63\x31\x18\x03 \x01(\x01\x12\n\n\x02\x63\x32\x18\x04 \x01(\x01\x12\n\n\x02\x63\x33\x18\x05 \x01(\x01\x12\t\n\x01\x66\x18\x06 \x01(\x01\x12\x0b\n\x03\x66un\x18\x07 \x01(\t\x12\x15\n\rscale_to_hfov\x18\x08 \x01(\x08\x12\x14\n\x0c\x63utoff_angle\x18\t \x01(\x01\x12\x0c\n\x04hfov\x18\n \x01(\x01\x12\x18\n\x10\x65nv_texture_size\x18\x0b \x01(\x05\x42\x1f\n\x0b\x63om.gz.msgsB\x10\x43\x61meraLensProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.camera_lens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\020CameraLensProtos'
  _globals['_CAMERALENS']._serialized_start=61
  _globals['_CAMERALENS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
