# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/cameratrack.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/cameratrack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gz/msgs/cameratrack.proto\x12\x07gz.msgs\x1a\x14gz/msgs/entity.proto\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/vector3d.proto\"\x95\x03\n\x0b\x43\x61meraTrack\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x32\n\ntrack_mode\x18\x02 \x01(\x0e\x32\x1e.gz.msgs.CameraTrack.TrackMode\x12&\n\rfollow_target\x18\x03 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12%\n\x0ctrack_target\x18\x04 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12(\n\rfollow_offset\x18\x05 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\'\n\x0ctrack_offset\x18\x06 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x14\n\x0c\x66ollow_pgain\x18\x07 \x01(\x01\x12\x13\n\x0btrack_pgain\x18\x08 \x01(\x01\"d\n\tTrackMode\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TRACK\x10\x01\x12\n\n\x06\x46OLLOW\x10\x02\x12\x14\n\x10\x46OLLOW_FREE_LOOK\x10\x03\x12\x12\n\x0e\x46OLLOW_LOOK_AT\x10\x04\x12\x0c\n\x08USE_LAST\x10\x05\x42 \n\x0b\x63om.gz.msgsB\x11\x43\x61meraTrackProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.cameratrack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\021CameraTrackProtos'
  _globals['_CAMERATRACK']._serialized_start=107
  _globals['_CAMERATRACK']._serialized_end=512
  _globals['_CAMERATRACK_TRACKMODE']._serialized_start=412
  _globals['_CAMERATRACK_TRACKMODE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
