# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/camerasensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/camerasensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import distortion_pb2 as gz_dot_msgs_dot_distortion__pb2
from gz.msgs import double_pb2 as gz_dot_msgs_dot_double__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import image_pb2 as gz_dot_msgs_dot_image__pb2
from gz.msgs import lens_pb2 as gz_dot_msgs_dot_lens__pb2
from gz.msgs import sensor_noise_pb2 as gz_dot_msgs_dot_sensor__noise__pb2
from gz.msgs import vector2d_pb2 as gz_dot_msgs_dot_vector2d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agz/msgs/camerasensor.proto\x12\x07gz.msgs\x1a\x18gz/msgs/distortion.proto\x1a\x14gz/msgs/double.proto\x1a\x14gz/msgs/header.proto\x1a\x13gz/msgs/image.proto\x1a\x12gz/msgs/lens.proto\x1a\x1agz/msgs/sensor_noise.proto\x1a\x16gz/msgs/vector2d.proto\"\xe2\x06\n\x0c\x43\x61meraSensor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x16\n\x0ehorizontal_fov\x18\x02 \x01(\x01\x12%\n\nimage_size\x18\x03 \x01(\x0b\x32\x11.gz.msgs.Vector2d\x12\x18\n\x0cimage_format\x18\x04 \x01(\tB\x02\x18\x01\x12\x11\n\tnear_clip\x18\x05 \x01(\x01\x12\x10\n\x08\x66\x61r_clip\x18\x06 \x01(\x01\x12\x14\n\x0csave_enabled\x18\x07 \x01(\x08\x12\x11\n\tsave_path\x18\x08 \x01(\t\x12\'\n\ndistortion\x18\t \x01(\x0b\x32\x13.gz.msgs.Distortion\x12)\n\x0bimage_noise\x18\n \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12(\n\x0f\x64\x65pth_near_clip\x18\x0b \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0e\x64\x65pth_far_clip\x18\x0c \x01(\x0b\x32\x0f.gz.msgs.Double\x12@\n\x11\x62ounding_box_type\x18\r \x01(\x0e\x32%.gz.msgs.CameraSensor.BoundingBoxType\x12\x41\n\x11segmentation_type\x18\x0e \x01(\x0e\x32&.gz.msgs.CameraSensor.SegmentationType\x12\x1b\n\x04lens\x18\x0f \x01(\x0b\x32\r.gz.msgs.Lens\x12\x11\n\ttriggered\x18\x10 \x01(\x08\x12\x17\n\x0ftriggered_topic\x18\x11 \x01(\t\x12\x15\n\ranti_aliasing\x18\x12 \x01(\x05\x12\x17\n\x0fvisibility_mask\x18\x13 \x01(\r\x12\x17\n\x0fis_depth_camera\x18\x14 \x01(\x08\x12.\n\x0cpixel_format\x18\x15 \x01(\x0e\x32\x18.gz.msgs.PixelFormatType\"W\n\x0f\x42oundingBoxType\x12\x13\n\x0fNO_BOUNDING_BOX\x10\x00\x12\x0f\n\x0b\x46ULL_BOX_2D\x10\x01\x12\x12\n\x0eVISIBLE_BOX_2D\x10\x02\x12\n\n\x06\x42OX_3D\x10\x03\"C\n\x10SegmentationType\x12\x13\n\x0fNO_SEGMENTATION\x10\x00\x12\x0c\n\x08SEMANTIC\x10\x01\x12\x0c\n\x08PANOPTIC\x10\x02\x42!\n\x0b\x63om.gz.msgsB\x12\x43\x61meraSensorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.camerasensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022CameraSensorProtos'
  _globals['_CAMERASENSOR'].fields_by_name['image_format']._loaded_options = None
  _globals['_CAMERASENSOR'].fields_by_name['image_format']._serialized_options = b'\030\001'
  _globals['_CAMERASENSOR']._serialized_start=203
  _globals['_CAMERASENSOR']._serialized_end=1069
  _globals['_CAMERASENSOR_BOUNDINGBOXTYPE']._serialized_start=913
  _globals['_CAMERASENSOR_BOUNDINGBOXTYPE']._serialized_end=1000
  _globals['_CAMERASENSOR_SEGMENTATIONTYPE']._serialized_start=1002
  _globals['_CAMERASENSOR_SEGMENTATIONTYPE']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
