# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/camera_info.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/camera_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gz/msgs/camera_info.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xe9\x03\n\nCameraInfo\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x32\n\ndistortion\x18\x04 \x01(\x0b\x32\x1e.gz.msgs.CameraInfo.Distortion\x12\x32\n\nintrinsics\x18\x05 \x01(\x0b\x32\x1e.gz.msgs.CameraInfo.Intrinsics\x12\x32\n\nprojection\x18\x06 \x01(\x0b\x32\x1e.gz.msgs.CameraInfo.Projection\x12 \n\x14rectification_matrix\x18\x07 \x03(\x01\x42\x02\x10\x01\x1a\xaa\x01\n\nDistortion\x12\x41\n\x05model\x18\x01 \x01(\x0e\x32\x32.gz.msgs.CameraInfo.Distortion.DistortionModelType\x12\t\n\x01k\x18\x02 \x03(\x01\"N\n\x13\x44istortionModelType\x12\r\n\tPLUMB_BOB\x10\x00\x12\x17\n\x13RATIONAL_POLYNOMIAL\x10\x01\x12\x0f\n\x0b\x45QUIDISTANT\x10\x02\x1a\x17\n\nIntrinsics\x12\t\n\x01k\x18\x01 \x03(\x01\x1a\x17\n\nProjection\x12\t\n\x01p\x18\x01 \x03(\x01\x42\x1f\n\x0b\x63om.gz.msgsB\x10\x43\x61meraInfoProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.camera_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\020CameraInfoProtos'
  _globals['_CAMERAINFO'].fields_by_name['rectification_matrix']._loaded_options = None
  _globals['_CAMERAINFO'].fields_by_name['rectification_matrix']._serialized_options = b'\020\001'
  _globals['_CAMERAINFO']._serialized_start=61
  _globals['_CAMERAINFO']._serialized_end=550
  _globals['_CAMERAINFO_DISTORTION']._serialized_start=330
  _globals['_CAMERAINFO_DISTORTION']._serialized_end=500
  _globals['_CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE']._serialized_start=422
  _globals['_CAMERAINFO_DISTORTION_DISTORTIONMODELTYPE']._serialized_end=500
  _globals['_CAMERAINFO_INTRINSICS']._serialized_start=502
  _globals['_CAMERAINFO_INTRINSICS']._serialized_end=525
  _globals['_CAMERAINFO_PROJECTION']._serialized_start=527
  _globals['_CAMERAINFO_PROJECTION']._serialized_end=550
# @@protoc_insertion_point(module_scope)
