# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/cessna.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/cessna.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gz/msgs/cessna.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xe5\x02\n\x06\x43\x65ssna\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x17\n\x0fpropeller_speed\x18\x02 \x01(\x02\x12\x14\n\x0cleft_aileron\x18\x03 \x01(\x02\x12\x11\n\tleft_flap\x18\x04 \x01(\x02\x12\x15\n\rright_aileron\x18\x05 \x01(\x02\x12\x12\n\nright_flap\x18\x06 \x01(\x02\x12\x11\n\televators\x18\x07 \x01(\x02\x12\x0e\n\x06rudder\x18\x08 \x01(\x02\x12\x1b\n\x13\x63md_propeller_speed\x18\t \x01(\x02\x12\x18\n\x10\x63md_left_aileron\x18\n \x01(\x02\x12\x15\n\rcmd_left_flap\x18\x0b \x01(\x02\x12\x19\n\x11\x63md_right_aileron\x18\x0c \x01(\x02\x12\x16\n\x0e\x63md_right_flap\x18\r \x01(\x02\x12\x15\n\rcmd_elevators\x18\x0e \x01(\x02\x12\x12\n\ncmd_rudder\x18\x0f \x01(\x02\x42\x1b\n\x0b\x63om.gz.msgsB\x0c\x43\x65ssnaProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.cessna_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014CessnaProtos'
  _globals['_CESSNA']._serialized_start=56
  _globals['_CESSNA']._serialized_end=413
# @@protoc_insertion_point(module_scope)
