# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/clock.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/clock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/clock.proto\x12\x07gz.msgs\x1a\x12gz/msgs/time.proto\x1a\x14gz/msgs/header.proto\"\x80\x01\n\x05\x43lock\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1d\n\x06system\x18\x02 \x01(\x0b\x32\r.gz.msgs.Time\x12\x1b\n\x04real\x18\x03 \x01(\x0b\x32\r.gz.msgs.Time\x12\x1a\n\x03sim\x18\x04 \x01(\x0b\x32\r.gz.msgs.TimeB\x1a\n\x0b\x63om.gz.msgsB\x0b\x43lockProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.clock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013ClockProtos'
  _globals['_CLOCK']._serialized_start=75
  _globals['_CLOCK']._serialized_end=203
# @@protoc_insertion_point(module_scope)
