# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/collision.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/collision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import geometry_pb2 as gz_dot_msgs_dot_geometry__pb2
from gz.msgs import surface_pb2 as gz_dot_msgs_dot_surface__pb2
from gz.msgs import visual_pb2 as gz_dot_msgs_dot_visual__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gz/msgs/collision.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x16gz/msgs/geometry.proto\x1a\x15gz/msgs/surface.proto\x1a\x14gz/msgs/visual.proto\x1a\x14gz/msgs/header.proto\"\xf7\x01\n\tCollision\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0blaser_retro\x18\x04 \x01(\x01\x12\x14\n\x0cmax_contacts\x18\x05 \x01(\x01\x12\x1b\n\x04pose\x18\x06 \x01(\x0b\x32\r.gz.msgs.Pose\x12#\n\x08geometry\x18\x07 \x01(\x0b\x32\x11.gz.msgs.Geometry\x12!\n\x07surface\x18\x08 \x01(\x0b\x32\x10.gz.msgs.Surface\x12\x1f\n\x06visual\x18\t \x03(\x0b\x32\x0f.gz.msgs.VisualB\x1e\n\x0b\x63om.gz.msgsB\x0f\x43ollisionProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.collision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017CollisionProtos'
  _globals['_COLLISION']._serialized_start=148
  _globals['_COLLISION']._serialized_end=395
# @@protoc_insertion_point(module_scope)
