# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/contacts.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/contacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import contact_pb2 as gz_dot_msgs_dot_contact__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/contacts.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x15gz/msgs/contact.proto\"N\n\x08\x43ontacts\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12!\n\x07\x63ontact\x18\x02 \x03(\x0b\x32\x10.gz.msgs.ContactB\x1d\n\x0b\x63om.gz.msgsB\x0e\x43ontactsProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.contacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\016ContactsProtos'
  _globals['_CONTACTS']._serialized_start=80
  _globals['_CONTACTS']._serialized_end=158
# @@protoc_insertion_point(module_scope)
