# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/contact.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/contact.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import joint_wrench_pb2 as gz_dot_msgs_dot_joint__wrench__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gz/msgs/contact.proto\x12\x07gz.msgs\x1a\x14gz/msgs/entity.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x1agz/msgs/joint_wrench.proto\x1a\x14gz/msgs/header.proto\"\x91\x02\n\x07\x43ontact\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12#\n\ncollision1\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12#\n\ncollision2\x18\x03 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12#\n\x08position\x18\x04 \x03(\x0b\x32\x11.gz.msgs.Vector3d\x12!\n\x06normal\x18\x05 \x03(\x0b\x32\x11.gz.msgs.Vector3d\x12\r\n\x05\x64\x65pth\x18\x06 \x03(\x01\x12$\n\x06wrench\x18\x07 \x03(\x0b\x32\x14.gz.msgs.JointWrench\x12\x1e\n\x05world\x18\x08 \x01(\x0b\x32\x0f.gz.msgs.EntityB\x1c\n\x0b\x63om.gz.msgsB\rContactProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.contact_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\rContactProtos'
  _globals['_CONTACT']._serialized_start=131
  _globals['_CONTACT']._serialized_end=404
# @@protoc_insertion_point(module_scope)
