# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/data_load_options.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/data_load_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import spherical_coordinates_pb2 as gz_dot_msgs_dot_spherical__coordinates__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgz/msgs/data_load_options.proto\x12\x07gz.msgs\x1a#gz/msgs/spherical_coordinates.proto\"\x8f\x02\n\x13\x44\x61taLoadPathOptions\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x13\n\x0bstatic_time\x18\x03 \x01(\x08\x12\t\n\x01x\x18\x04 \x01(\t\x12\t\n\x01y\x18\x05 \x01(\t\x12\t\n\x01z\x18\x06 \x01(\t\x12<\n\x05units\x18\x07 \x01(\x0e\x32-.gz.msgs.DataLoadPathOptions.DataAngularUnits\x12:\n\x0f\x63oordinate_type\x18\x08 \x01(\x0e\x32!.gz.msgs.SphericalCoordinatesType\",\n\x10\x44\x61taAngularUnits\x12\x0b\n\x07RADIANS\x10\x00\x12\x0b\n\x07\x44\x45GREES\x10\x01\x42\"\n\x0b\x63om.gz.msgsB\x13\x44\x61taLoadPathOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.data_load_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023DataLoadPathOptions'
  _globals['_DATALOADPATHOPTIONS']._serialized_start=82
  _globals['_DATALOADPATHOPTIONS']._serialized_end=353
  _globals['_DATALOADPATHOPTIONS_DATAANGULARUNITS']._serialized_start=309
  _globals['_DATALOADPATHOPTIONS_DATAANGULARUNITS']._serialized_end=353
# @@protoc_insertion_point(module_scope)
