# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/distortion.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/distortion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector2d_pb2 as gz_dot_msgs_dot_vector2d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/distortion.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector2d.proto\x1a\x14gz/msgs/header.proto\"\x8c\x01\n\nDistortion\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12!\n\x06\x63\x65nter\x18\x02 \x01(\x0b\x32\x11.gz.msgs.Vector2d\x12\n\n\x02k1\x18\x03 \x01(\x01\x12\n\n\x02k2\x18\x04 \x01(\x01\x12\n\n\x02k3\x18\x05 \x01(\x01\x12\n\n\x02p1\x18\x06 \x01(\x01\x12\n\n\x02p2\x18\x07 \x01(\x01\x42\x1f\n\x0b\x63om.gz.msgsB\x10\x44istortionProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.distortion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\020DistortionProtos'
  _globals['_DISTORTION']._serialized_start=84
  _globals['_DISTORTION']._serialized_end=224
# @@protoc_insertion_point(module_scope)
