# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/dvl_tracking_target.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/dvl_tracking_target.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import dvl_kinematic_estimate_pb2 as gz_dot_msgs_dot_dvl__kinematic__estimate__pb2
from gz.msgs import dvl_range_estimate_pb2 as gz_dot_msgs_dot_dvl__range__estimate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!gz/msgs/dvl_tracking_target.proto\x12\x07gz.msgs\x1a$gz/msgs/dvl_kinematic_estimate.proto\x1a gz/msgs/dvl_range_estimate.proto\"\xff\x01\n\x11\x44VLTrackingTarget\x12\x33\n\x04type\x18\x01 \x01(\x0e\x32%.gz.msgs.DVLTrackingTarget.TargetType\x12(\n\x05range\x18\x02 \x01(\x0b\x32\x19.gz.msgs.DVLRangeEstimate\x12/\n\x08position\x18\x03 \x01(\x0b\x32\x1d.gz.msgs.DVLKinematicEstimate\"Z\n\nTargetType\x12\x1a\n\x16\x44VL_TARGET_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44VL_TARGET_BOTTOM\x10\x01\x12\x19\n\x15\x44VL_TARGET_WATER_MASS\x10\x02\x42&\n\x0b\x63om.gz.msgsB\x17\x44VLTrackingTargetProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.dvl_tracking_target_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\027DVLTrackingTargetProtos'
  _globals['_DVLTRACKINGTARGET']._serialized_start=119
  _globals['_DVLTRACKINGTARGET']._serialized_end=374
  _globals['_DVLTRACKINGTARGET_TARGETTYPE']._serialized_start=284
  _globals['_DVLTRACKINGTARGET_TARGETTYPE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
