# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/dvl_velocity_tracking.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/dvl_velocity_tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import dvl_beam_state_pb2 as gz_dot_msgs_dot_dvl__beam__state__pb2
from gz.msgs import dvl_tracking_target_pb2 as gz_dot_msgs_dot_dvl__tracking__target__pb2
from gz.msgs import dvl_kinematic_estimate_pb2 as gz_dot_msgs_dot_dvl__kinematic__estimate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#gz/msgs/dvl_velocity_tracking.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x1cgz/msgs/dvl_beam_state.proto\x1a!gz/msgs/dvl_tracking_target.proto\x1a$gz/msgs/dvl_kinematic_estimate.proto\"\xd2\x02\n\x13\x44VLVelocityTracking\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.gz.msgs.DVLVelocityTracking.DVLType\x12*\n\x06target\x18\x03 \x01(\x0b\x32\x1a.gz.msgs.DVLTrackingTarget\x12/\n\x08velocity\x18\x04 \x01(\x0b\x32\x1d.gz.msgs.DVLKinematicEstimate\x12$\n\x05\x62\x65\x61ms\x18\x05 \x03(\x0b\x32\x15.gz.msgs.DVLBeamState\x12\x0e\n\x06status\x18\x06 \x01(\x05\"S\n\x07\x44VLType\x12\x18\n\x14\x44VL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44VL_TYPE_PISTON\x10\x01\x12\x19\n\x15\x44VL_TYPE_PHASED_ARRAY\x10\x02\x42(\n\x0b\x63om.gz.msgsB\x19\x44VLVelocityTrackingProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.dvl_velocity_tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\031DVLVelocityTrackingProtos'
  _globals['_DVLVELOCITYTRACKING']._serialized_start=174
  _globals['_DVLVELOCITYTRACKING']._serialized_end=512
  _globals['_DVLVELOCITYTRACKING_DVLTYPE']._serialized_start=429
  _globals['_DVLVELOCITYTRACKING_DVLTYPE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
