# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/dvl_beam_state.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/dvl_beam_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import dvl_kinematic_estimate_pb2 as gz_dot_msgs_dot_dvl__kinematic__estimate__pb2
from gz.msgs import dvl_range_estimate_pb2 as gz_dot_msgs_dot_dvl__range__estimate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/dvl_beam_state.proto\x12\x07gz.msgs\x1a$gz/msgs/dvl_kinematic_estimate.proto\x1a gz/msgs/dvl_range_estimate.proto\"\xa0\x01\n\x0c\x44VLBeamState\x12\n\n\x02id\x18\x01 \x01(\x05\x12/\n\x08velocity\x18\x02 \x01(\x0b\x32\x1d.gz.msgs.DVLKinematicEstimate\x12(\n\x05range\x18\x03 \x01(\x0b\x32\x19.gz.msgs.DVLRangeEstimate\x12\x0c\n\x04rssi\x18\x04 \x01(\x01\x12\x0b\n\x03nsd\x18\x05 \x01(\x01\x12\x0e\n\x06locked\x18\x06 \x01(\x08\x42!\n\x0b\x63om.gz.msgsB\x12\x44VLBeamStateProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.dvl_beam_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022DVLBeamStateProtos'
  _globals['_DVLBEAMSTATE']._serialized_start=114
  _globals['_DVLBEAMSTATE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
