# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/entity_wrench_map.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/entity_wrench_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_wrench_pb2 as gz_dot_msgs_dot_entity__wrench__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgz/msgs/entity_wrench_map.proto\x12\x07gz.msgs\x1a\x1bgz/msgs/entity_wrench.proto\x1a\x14gz/msgs/header.proto\"\xb4\x01\n\x0f\x45ntityWrenchMap\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x38\n\x08wrenches\x18\x02 \x03(\x0b\x32&.gz.msgs.EntityWrenchMap.WrenchesEntry\x1a\x46\n\rWrenchesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.gz.msgs.EntityWrench:\x02\x38\x01\x42$\n\x0b\x63om.gz.msgsB\x15\x45ntityWrenchMapProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.entity_wrench_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\025EntityWrenchMapProtos'
  _globals['_ENTITYWRENCHMAP_WRENCHESENTRY']._loaded_options = None
  _globals['_ENTITYWRENCHMAP_WRENCHESENTRY']._serialized_options = b'8\001'
  _globals['_ENTITYWRENCHMAP']._serialized_start=96
  _globals['_ENTITYWRENCHMAP']._serialized_end=276
  _globals['_ENTITYWRENCHMAP_WRENCHESENTRY']._serialized_start=206
  _globals['_ENTITYWRENCHMAP_WRENCHESENTRY']._serialized_end=276
# @@protoc_insertion_point(module_scope)
