# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/entity_factory_v.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/entity_factory_v.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_factory_pb2 as gz_dot_msgs_dot_entity__factory__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egz/msgs/entity_factory_v.proto\x12\x07gz.msgs\x1a\x1cgz/msgs/entity_factory.proto\x1a\x14gz/msgs/header.proto\"X\n\x0f\x45ntityFactory_V\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.gz.msgs.EntityFactoryB#\n\x0b\x63om.gz.msgsB\x14\x45ntityFactoryVProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.entity_factory_v_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\024EntityFactoryVProtos'
  _globals['_ENTITYFACTORY_V']._serialized_start=95
  _globals['_ENTITYFACTORY_V']._serialized_end=183
# @@protoc_insertion_point(module_scope)
