# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/fog.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/fog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/fog.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/header.proto\"\xda\x01\n\x03\x46og\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.gz.msgs.Fog.FogType\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x0f\n\x07\x64\x65nsity\x18\x04 \x01(\x02\x12\r\n\x05start\x18\x05 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x02\"B\n\x07\x46ogType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06LINEAR\x10\x01\x12\x0f\n\x0b\x45XPONENTIAL\x10\x02\x12\x10\n\x0c\x45XPONENTIAL2\x10\x03\x42\x18\n\x0b\x63om.gz.msgsB\tFogProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.fog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\tFogProtos'
  _globals['_FOG']._serialized_start=74
  _globals['_FOG']._serialized_end=292
  _globals['_FOG_FOGTYPE']._serialized_start=226
  _globals['_FOG_FOGTYPE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
