# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/friction.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/friction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/friction.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xe2\x02\n\x08\x46riction\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02mu\x18\x02 \x01(\x01\x12\x0b\n\x03mu2\x18\x03 \x01(\x01\x12 \n\x05\x66\x64ir1\x18\x04 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\r\n\x05slip1\x18\x05 \x01(\x01\x12\r\n\x05slip2\x18\x06 \x01(\x01\x12.\n\ttorsional\x18\x07 \x01(\x0b\x32\x1b.gz.msgs.Friction.Torsional\x1a\xab\x01\n\tTorsional\x12\x13\n\x0b\x63oefficient\x18\x01 \x01(\x01\x12\x18\n\x10use_patch_radius\x18\x02 \x01(\x08\x12\x14\n\x0cpatch_radius\x18\x03 \x01(\x01\x12\x16\n\x0esurface_radius\x18\x04 \x01(\x01\x12,\n\x03ode\x18\x05 \x01(\x0b\x32\x1f.gz.msgs.Friction.Torsional.ODE\x1a\x13\n\x03ODE\x12\x0c\n\x04slip\x18\x01 \x01(\x01\x42\x1d\n\x0b\x63om.gz.msgsB\x0e\x46rictionProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.friction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\016FrictionProtos'
  _globals['_FRICTION']._serialized_start=82
  _globals['_FRICTION']._serialized_end=436
  _globals['_FRICTION_TORSIONAL']._serialized_start=265
  _globals['_FRICTION_TORSIONAL']._serialized_end=436
  _globals['_FRICTION_TORSIONAL_ODE']._serialized_start=417
  _globals['_FRICTION_TORSIONAL_ODE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
