# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/geometry.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import boxgeom_pb2 as gz_dot_msgs_dot_boxgeom__pb2
from gz.msgs import capsulegeom_pb2 as gz_dot_msgs_dot_capsulegeom__pb2
from gz.msgs import conegeom_pb2 as gz_dot_msgs_dot_conegeom__pb2
from gz.msgs import cylindergeom_pb2 as gz_dot_msgs_dot_cylindergeom__pb2
from gz.msgs import ellipsoidgeom_pb2 as gz_dot_msgs_dot_ellipsoidgeom__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import heightmapgeom_pb2 as gz_dot_msgs_dot_heightmapgeom__pb2
from gz.msgs import imagegeom_pb2 as gz_dot_msgs_dot_imagegeom__pb2
from gz.msgs import meshgeom_pb2 as gz_dot_msgs_dot_meshgeom__pb2
from gz.msgs import planegeom_pb2 as gz_dot_msgs_dot_planegeom__pb2
from gz.msgs import polylinegeom_pb2 as gz_dot_msgs_dot_polylinegeom__pb2
from gz.msgs import spheregeom_pb2 as gz_dot_msgs_dot_spheregeom__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/geometry.proto\x12\x07gz.msgs\x1a\x15gz/msgs/boxgeom.proto\x1a\x19gz/msgs/capsulegeom.proto\x1a\x16gz/msgs/conegeom.proto\x1a\x1agz/msgs/cylindergeom.proto\x1a\x1bgz/msgs/ellipsoidgeom.proto\x1a\x14gz/msgs/header.proto\x1a\x1bgz/msgs/heightmapgeom.proto\x1a\x17gz/msgs/imagegeom.proto\x1a\x16gz/msgs/meshgeom.proto\x1a\x17gz/msgs/planegeom.proto\x1a\x1agz/msgs/polylinegeom.proto\x1a\x18gz/msgs/spheregeom.proto\x1a\x16gz/msgs/vector3d.proto\"\xdc\x05\n\x08Geometry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.gz.msgs.Geometry.Type\x12\x1d\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x10.gz.msgs.BoxGeom\x12\'\n\x08\x63ylinder\x18\x04 \x01(\x0b\x32\x15.gz.msgs.CylinderGeom\x12!\n\x05plane\x18\x05 \x01(\x0b\x32\x12.gz.msgs.PlaneGeom\x12#\n\x06sphere\x18\x06 \x01(\x0b\x32\x13.gz.msgs.SphereGeom\x12!\n\x05image\x18\x07 \x01(\x0b\x32\x12.gz.msgs.ImageGeom\x12)\n\theightmap\x18\x08 \x01(\x0b\x32\x16.gz.msgs.HeightmapGeom\x12\x1f\n\x04mesh\x18\t \x01(\x0b\x32\x11.gz.msgs.MeshGeom\x12\x1f\n\x04\x63one\x18\n \x01(\x0b\x32\x11.gz.msgs.ConeGeom\x12%\n\x07\x63\x61psule\x18\r \x01(\x0b\x32\x14.gz.msgs.CapsuleGeom\x12)\n\tellipsoid\x18\x0e \x01(\x0b\x32\x16.gz.msgs.EllipsoidGeom\x12!\n\x06points\x18\x0b \x03(\x0b\x32\x11.gz.msgs.Vector3d\x12#\n\x08polyline\x18\x0c \x03(\x0b\x32\x11.gz.msgs.Polyline\"\xce\x01\n\x04Type\x12\x07\n\x03\x42OX\x10\x00\x12\x0c\n\x08\x43YLINDER\x10\x01\x12\n\n\x06SPHERE\x10\x02\x12\t\n\x05PLANE\x10\x03\x12\t\n\x05IMAGE\x10\x04\x12\r\n\tHEIGHTMAP\x10\x05\x12\x08\n\x04MESH\x10\x06\x12\x10\n\x0cTRIANGLE_FAN\x10\x07\x12\x0e\n\nLINE_STRIP\x10\x08\x12\x0c\n\x08POLYLINE\x10\t\x12\x08\n\x04\x43ONE\x10\n\x12\t\n\x05\x45MPTY\x10\x0b\x12\t\n\x05\x41RROW\x10\x0c\x12\x08\n\x04\x41XIS\x10\r\x12\x0b\n\x07\x43\x41PSULE\x10\x0e\x12\r\n\tELLIPSOID\x10\x0f\x42\x1d\n\x0b\x63om.gz.msgsB\x0eGeometryProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\016GeometryProtos'
  _globals['_GEOMETRY']._serialized_start=370
  _globals['_GEOMETRY']._serialized_end=1102
  _globals['_GEOMETRY_TYPE']._serialized_start=896
  _globals['_GEOMETRY_TYPE']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
