# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/gui.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/gui.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import gui_camera_pb2 as gz_dot_msgs_dot_gui__camera__pb2
from gz.msgs import plugin_pb2 as gz_dot_msgs_dot_plugin__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/gui.proto\x12\x07gz.msgs\x1a\x18gz/msgs/gui_camera.proto\x1a\x14gz/msgs/plugin.proto\x1a\x14gz/msgs/header.proto\"\x7f\n\x03GUI\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x12\n\nfullscreen\x18\x02 \x01(\x08\x12\"\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x12.gz.msgs.GUICamera\x12\x1f\n\x06plugin\x18\x04 \x03(\x0b\x32\x0f.gz.msgs.PluginB\x18\n\x0b\x63om.gz.msgsB\tGUIProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.gui_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\tGUIProtos'
  _globals['_GUI']._serialized_start=100
  _globals['_GUI']._serialized_end=227
# @@protoc_insertion_point(module_scope)
