# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/gui_camera.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/gui_camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import track_visual_pb2 as gz_dot_msgs_dot_track__visual__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/gui_camera.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x1agz/msgs/track_visual.proto\x1a\x14gz/msgs/header.proto\"\xc0\x01\n\tGUICamera\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fview_controller\x18\x03 \x01(\t\x12\x1b\n\x04pose\x18\x04 \x01(\x0b\x32\r.gz.msgs.Pose\x12#\n\x05track\x18\x05 \x01(\x0b\x32\x14.gz.msgs.TrackVisual\x12\x17\n\x0fprojection_type\x18\x06 \x01(\t\x12\x10\n\x08\x64uration\x18\x07 \x01(\x01\x42\x1e\n\x0b\x63om.gz.msgsB\x0fGUICameraProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.gui_camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017GUICameraProtos'
  _globals['_GUICAMERA']._serialized_start=108
  _globals['_GUICAMERA']._serialized_end=300
# @@protoc_insertion_point(module_scope)
