# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/heightmapgeom.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/heightmapgeom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import image_pb2 as gz_dot_msgs_dot_image__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/heightmapgeom.proto\x12\x07gz.msgs\x1a\x13gz/msgs/image.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xcb\x03\n\rHeightmapGeom\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1d\n\x05image\x18\x02 \x01(\x0b\x32\x0e.gz.msgs.Image\x12\x1f\n\x04size\x18\x03 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12!\n\x06origin\x18\x04 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x0f\n\x07heights\x18\x05 \x03(\x02\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\x12/\n\x07texture\x18\x08 \x03(\x0b\x32\x1e.gz.msgs.HeightmapGeom.Texture\x12+\n\x05\x62lend\x18\t \x03(\x0b\x32\x1c.gz.msgs.HeightmapGeom.Blend\x12\x1a\n\x12use_terrain_paging\x18\n \x01(\x08\x12\x10\n\x08\x66ilename\x18\x0b \x01(\t\x12\x10\n\x08sampling\x18\x0c \x01(\r\x1a\x38\n\x07Texture\x12\x0f\n\x07\x64iffuse\x18\x01 \x01(\t\x12\x0e\n\x06normal\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x01\x1a.\n\x05\x42lend\x12\x12\n\nmin_height\x18\x01 \x01(\x01\x12\x11\n\tfade_dist\x18\x02 \x01(\x01\x42\"\n\x0b\x63om.gz.msgsB\x13HeightmapGeomProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.heightmapgeom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023HeightmapGeomProtos'
  _globals['_HEIGHTMAPGEOM']._serialized_start=108
  _globals['_HEIGHTMAPGEOM']._serialized_end=567
  _globals['_HEIGHTMAPGEOM_TEXTURE']._serialized_start=463
  _globals['_HEIGHTMAPGEOM_TEXTURE']._serialized_end=519
  _globals['_HEIGHTMAPGEOM_BLEND']._serialized_start=521
  _globals['_HEIGHTMAPGEOM_BLEND']._serialized_end=567
# @@protoc_insertion_point(module_scope)
