# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/hydra.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/hydra.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/hydra.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/header.proto\"\xd4\x02\n\x05Hydra\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12$\n\x05right\x18\x02 \x01(\x0b\x32\x15.gz.msgs.Hydra.Paddle\x12#\n\x04left\x18\x03 \x01(\x0b\x32\x15.gz.msgs.Hydra.Paddle\x1a\xde\x01\n\x06Paddle\x12\x1b\n\x04pose\x18\x01 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x15\n\rbutton_bumper\x18\x02 \x01(\x08\x12\x10\n\x08\x62utton_1\x18\x03 \x01(\x08\x12\x10\n\x08\x62utton_2\x18\x04 \x01(\x08\x12\x10\n\x08\x62utton_3\x18\x05 \x01(\x08\x12\x10\n\x08\x62utton_4\x18\x06 \x01(\x08\x12\x12\n\nbutton_joy\x18\x07 \x01(\x08\x12\x15\n\rbutton_center\x18\x08 \x01(\x08\x12\r\n\x05joy_x\x18\t \x01(\x01\x12\r\n\x05joy_y\x18\n \x01(\x01\x12\x0f\n\x07trigger\x18\x0b \x01(\x01\x42\x1a\n\x0b\x63om.gz.msgsB\x0bHydraProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.hydra_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013HydraProtos'
  _globals['_HYDRA']._serialized_start=75
  _globals['_HYDRA']._serialized_end=415
  _globals['_HYDRA_PADDLE']._serialized_start=193
  _globals['_HYDRA_PADDLE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
