# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/imu.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import quaternion_pb2 as gz_dot_msgs_dot_quaternion__pb2
from gz.msgs import float_v_pb2 as gz_dot_msgs_dot_float__v__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/imu.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x18gz/msgs/quaternion.proto\x1a\x15gz/msgs/float_v.proto\"\xe5\x02\n\x03IMU\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x13\n\x0b\x65ntity_name\x18\x02 \x01(\t\x12(\n\x0borientation\x18\x03 \x01(\x0b\x32\x13.gz.msgs.Quaternion\x12\x30\n\x16orientation_covariance\x18\x04 \x01(\x0b\x32\x10.gz.msgs.Float_V\x12+\n\x10\x61ngular_velocity\x18\x05 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x35\n\x1b\x61ngular_velocity_covariance\x18\x06 \x01(\x0b\x32\x10.gz.msgs.Float_V\x12.\n\x13linear_acceleration\x18\x07 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x38\n\x1elinear_acceleration_covariance\x18\x08 \x01(\x0b\x32\x10.gz.msgs.Float_VB\x18\n\x0b\x63om.gz.msgsB\tIMUProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\tIMUProtos'
  _globals['_IMU']._serialized_start=126
  _globals['_IMU']._serialized_end=483
# @@protoc_insertion_point(module_scope)
