# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/imu_sensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/imu_sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import sensor_noise_pb2 as gz_dot_msgs_dot_sensor__noise__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/imu_sensor.proto\x12\x07gz.msgs\x1a\x1agz/msgs/sensor_noise.proto\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/vector3d.proto\"\xda\x05\n\tIMUSensor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12<\n\x10\x61ngular_velocity\x18\x02 \x01(\x0b\x32\".gz.msgs.IMUSensor.AngularVelocity\x12\x42\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32%.gz.msgs.IMUSensor.LinearAcceleration\x12K\n\x15orientation_ref_frame\x18\x04 \x01(\x0b\x32,.gz.msgs.IMUSensor.OrientationReferenceFrame\x1a\x86\x01\n\x0f\x41ngularVelocity\x12%\n\x07x_noise\x18\x01 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12%\n\x07y_noise\x18\x02 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12%\n\x07z_noise\x18\x03 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x1a\x89\x01\n\x12LinearAcceleration\x12%\n\x07x_noise\x18\x01 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12%\n\x07y_noise\x18\x02 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12%\n\x07z_noise\x18\x03 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x1a\xc7\x01\n\x19OrientationReferenceFrame\x12\x14\n\x0clocalization\x18\x01 \x01(\t\x12%\n\ncustom_rpy\x18\x02 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x1f\n\x17\x63ustom_rpy_parent_frame\x18\x03 \x01(\t\x12(\n\rgravity_dir_x\x18\x04 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\"\n\x1agravity_dir_x_parent_frame\x18\x05 \x01(\tB\x1e\n\x0b\x63om.gz.msgsB\x0fIMUSensorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.imu_sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017IMUSensorProtos'
  _globals['_IMUSENSOR']._serialized_start=112
  _globals['_IMUSENSOR']._serialized_end=842
  _globals['_IMUSENSOR_ANGULARVELOCITY']._serialized_start=366
  _globals['_IMUSENSOR_ANGULARVELOCITY']._serialized_end=500
  _globals['_IMUSENSOR_LINEARACCELERATION']._serialized_start=503
  _globals['_IMUSENSOR_LINEARACCELERATION']._serialized_end=640
  _globals['_IMUSENSOR_ORIENTATIONREFERENCEFRAME']._serialized_start=643
  _globals['_IMUSENSOR_ORIENTATIONREFERENCEFRAME']._serialized_end=842
# @@protoc_insertion_point(module_scope)
