# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/joint_animation.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/joint_animation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgz/msgs/joint_animation.proto\x12\x07gz.msgs\x1a\x12gz/msgs/time.proto\x1a\x14gz/msgs/header.proto\"\xb6\x01\n\x0eJointAnimation\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12,\n\x05joint\x18\x03 \x03(\x0b\x32\x1d.gz.msgs.JointAnimation.Joint\x12\x1b\n\x04time\x18\x04 \x03(\x0b\x32\r.gz.msgs.Time\x1a$\n\x05Joint\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\r\n\x05\x61ngle\x18\x02 \x03(\x01\x42#\n\x0b\x63om.gz.msgsB\x14JointAnimationProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.joint_animation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\024JointAnimationProtos'
  _globals['_JOINTANIMATION']._serialized_start=85
  _globals['_JOINTANIMATION']._serialized_end=267
  _globals['_JOINTANIMATION_JOINT']._serialized_start=231
  _globals['_JOINTANIMATION_JOINT']._serialized_end=267
# @@protoc_insertion_point(module_scope)
