# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/joint.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/joint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import axis_pb2 as gz_dot_msgs_dot_axis__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import sensor_pb2 as gz_dot_msgs_dot_sensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/joint.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/axis.proto\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/sensor.proto\"\xdb\x05\n\x05Joint\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12!\n\x04type\x18\x04 \x01(\x0e\x32\x13.gz.msgs.Joint.Type\x12\x0e\n\x06parent\x18\x05 \x01(\t\x12\x11\n\tparent_id\x18\x06 \x01(\r\x12\r\n\x05\x63hild\x18\x07 \x01(\t\x12\x10\n\x08\x63hild_id\x18\x08 \x01(\r\x12\x1b\n\x04pose\x18\t \x01(\x0b\x32\r.gz.msgs.Pose\x12\x1c\n\x05\x61xis1\x18\n \x01(\x0b\x32\r.gz.msgs.Axis\x12\x1c\n\x05\x61xis2\x18\x0b \x01(\x0b\x32\r.gz.msgs.Axis\x12\x0b\n\x03\x63\x66m\x18\x0c \x01(\x01\x12\x0e\n\x06\x62ounce\x18\r \x01(\x01\x12\x14\n\x0c\x66udge_factor\x18\x0e \x01(\x01\x12\x11\n\tlimit_cfm\x18\x0f \x01(\x01\x12\x11\n\tlimit_erp\x18\x10 \x01(\x01\x12\x16\n\x0esuspension_cfm\x18\x11 \x01(\x01\x12\x16\n\x0esuspension_erp\x18\x12 \x01(\x01\x12\'\n\x07gearbox\x18\x13 \x01(\x0b\x32\x16.gz.msgs.Joint.Gearbox\x12#\n\x05screw\x18\x14 \x01(\x0b\x32\x14.gz.msgs.Joint.Screw\x12\x1f\n\x06sensor\x18\x15 \x03(\x0b\x32\x0f.gz.msgs.Sensor\x1a@\n\x07Gearbox\x12\x1e\n\x16gearbox_reference_body\x18\x01 \x01(\t\x12\x15\n\rgearbox_ratio\x18\x02 \x01(\x01\x1a\x1d\n\x05Screw\x12\x14\n\x0cthread_pitch\x18\x01 \x01(\x01\"~\n\x04Type\x12\x0c\n\x08REVOLUTE\x10\x00\x12\r\n\tREVOLUTE2\x10\x01\x12\r\n\tPRISMATIC\x10\x02\x12\r\n\tUNIVERSAL\x10\x03\x12\x08\n\x04\x42\x41LL\x10\x04\x12\t\n\x05SCREW\x10\x05\x12\x0b\n\x07GEARBOX\x10\x06\x12\t\n\x05\x46IXED\x10\x07\x12\x0e\n\nCONTINUOUS\x10\x08\x42\x1a\n\x0b\x63om.gz.msgsB\x0bJointProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.joint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013JointProtos'
  _globals['_JOINT']._serialized_start=117
  _globals['_JOINT']._serialized_end=848
  _globals['_JOINT_GEARBOX']._serialized_start=625
  _globals['_JOINT_GEARBOX']._serialized_end=689
  _globals['_JOINT_SCREW']._serialized_start=691
  _globals['_JOINT_SCREW']._serialized_end=720
  _globals['_JOINT_TYPE']._serialized_start=722
  _globals['_JOINT_TYPE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
