# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/laserscan.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/laserscan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gz/msgs/laserscan.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/header.proto\"\xdf\x02\n\tLaserScan\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\r\n\x05\x66rame\x18\x02 \x01(\t\x12!\n\nworld_pose\x18\x03 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x11\n\tangle_min\x18\x04 \x01(\x01\x12\x11\n\tangle_max\x18\x05 \x01(\x01\x12\x12\n\nangle_step\x18\x06 \x01(\x01\x12\x11\n\trange_min\x18\x07 \x01(\x01\x12\x11\n\trange_max\x18\x08 \x01(\x01\x12\r\n\x05\x63ount\x18\t \x01(\r\x12\x1a\n\x12vertical_angle_min\x18\n \x01(\x01\x12\x1a\n\x12vertical_angle_max\x18\x0b \x01(\x01\x12\x1b\n\x13vertical_angle_step\x18\x0c \x01(\x01\x12\x16\n\x0evertical_count\x18\r \x01(\r\x12\x0e\n\x06ranges\x18\x0e \x03(\x01\x12\x13\n\x0bintensities\x18\x0f \x03(\x01\x42\x1e\n\x0b\x63om.gz.msgsB\x0fLaserScanProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.laserscan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017LaserScanProtos'
  _globals['_LASERSCAN']._serialized_start=79
  _globals['_LASERSCAN']._serialized_end=430
# @@protoc_insertion_point(module_scope)
