# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/lens.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/lens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gz/msgs/lens.proto\x12\x07gz.msgs\"\xa7\x04\n\x04Lens\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.gz.msgs.Lens.Type\x12\x15\n\rscale_to_hfov\x18\x02 \x01(\x08\x12\n\n\x02\x63\x31\x18\x03 \x01(\x01\x12\n\n\x02\x63\x32\x18\x04 \x01(\x01\x12\n\n\x02\x63\x33\x18\x05 \x01(\x01\x12\x14\n\x0c\x66ocal_length\x18\x06 \x01(\x01\x12\x31\n\rfunction_type\x18\x07 \x01(\x0e\x32\x1a.gz.msgs.Lens.FunctionType\x12\x14\n\x0c\x63utoff_angle\x18\x08 \x01(\x01\x12 \n\x18\x65nvironment_texture_size\x18\t \x01(\x05\x12\x15\n\rintrinsics_fx\x18\n \x01(\x01\x12\x15\n\rintrinsics_fy\x18\x0b \x01(\x01\x12\x15\n\rintrinsics_cx\x18\x0c \x01(\x01\x12\x15\n\rintrinsics_cy\x18\r \x01(\x01\x12\x17\n\x0fintrinsics_skew\x18\x0e \x01(\x01\"\x85\x01\n\x04Type\x12\x16\n\x12TYPE_NOT_SPECIFIED\x10\x00\x12\x0e\n\nGNOMONICAL\x10\x01\x12\x11\n\rSTEREOGRAPHIC\x10\x02\x12\x0f\n\x0b\x45QUIDISTANT\x10\x03\x12\x13\n\x0f\x45QUISOLID_ANGLE\x10\x04\x12\x10\n\x0cORTHOGRAPHIC\x10\x05\x12\n\n\x06\x43USTOM\x10\x06\"D\n\x0c\x46unctionType\x12\x1a\n\x16\x46UNCTION_NOT_SPECIFIED\x10\x00\x12\x07\n\x03SIN\x10\x01\x12\x07\n\x03TAN\x10\x02\x12\x06\n\x02ID\x10\x03\x42\x19\n\x0b\x63om.gz.msgsB\nLensProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.lens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\nLensProtos'
  _globals['_LENS']._serialized_start=32
  _globals['_LENS']._serialized_end=583
  _globals['_LENS_TYPE']._serialized_start=380
  _globals['_LENS_TYPE']._serialized_end=513
  _globals['_LENS_FUNCTIONTYPE']._serialized_start=515
  _globals['_LENS_FUNCTIONTYPE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
