# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/lidar_sensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/lidar_sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import sensor_noise_pb2 as gz_dot_msgs_dot_sensor__noise__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agz/msgs/lidar_sensor.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x1agz/msgs/sensor_noise.proto\"\x8f\x03\n\x0bLidarSensor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x14\n\x0c\x64isplay_scan\x18\x02 \x01(\x08\x12\x1a\n\x12horizontal_samples\x18\x03 \x01(\x05\x12\x1d\n\x15horizontal_resolution\x18\x04 \x01(\x01\x12\x1c\n\x14horizontal_min_angle\x18\x05 \x01(\x01\x12\x1c\n\x14horizontal_max_angle\x18\x06 \x01(\x01\x12\x18\n\x10vertical_samples\x18\x07 \x01(\x05\x12\x1b\n\x13vertical_resolution\x18\x08 \x01(\x01\x12\x1a\n\x12vertical_min_angle\x18\t \x01(\x01\x12\x1a\n\x12vertical_max_angle\x18\n \x01(\x01\x12\x11\n\trange_min\x18\x0b \x01(\x01\x12\x11\n\trange_max\x18\x0c \x01(\x01\x12\x18\n\x10range_resolution\x18\r \x01(\x01\x12#\n\x05noise\x18\x0e \x01(\x0b\x32\x14.gz.msgs.SensorNoiseB \n\x0b\x63om.gz.msgsB\x11LidarSensorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.lidar_sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\021LidarSensorProtos'
  _globals['_LIDARSENSOR']._serialized_start=90
  _globals['_LIDARSENSOR']._serialized_end=489
# @@protoc_insertion_point(module_scope)
