# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/link.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/link.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import inertial_pb2 as gz_dot_msgs_dot_inertial__pb2
from gz.msgs import collision_pb2 as gz_dot_msgs_dot_collision__pb2
from gz.msgs import visual_pb2 as gz_dot_msgs_dot_visual__pb2
from gz.msgs import light_pb2 as gz_dot_msgs_dot_light__pb2
from gz.msgs import sensor_pb2 as gz_dot_msgs_dot_sensor__pb2
from gz.msgs import particle_emitter_pb2 as gz_dot_msgs_dot_particle__emitter__pb2
from gz.msgs import projector_pb2 as gz_dot_msgs_dot_projector__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import battery_pb2 as gz_dot_msgs_dot_battery__pb2
from gz.msgs import density_pb2 as gz_dot_msgs_dot_density__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gz/msgs/link.proto\x12\x07gz.msgs\x1a\x16gz/msgs/inertial.proto\x1a\x17gz/msgs/collision.proto\x1a\x14gz/msgs/visual.proto\x1a\x13gz/msgs/light.proto\x1a\x14gz/msgs/sensor.proto\x1a\x1egz/msgs/particle_emitter.proto\x1a\x17gz/msgs/projector.proto\x1a\x12gz/msgs/pose.proto\x1a\x15gz/msgs/battery.proto\x1a\x15gz/msgs/density.proto\x1a\x14gz/msgs/header.proto\"\x8a\x04\n\x04Link\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0cself_collide\x18\x04 \x01(\x08\x12\x0f\n\x07gravity\x18\x05 \x01(\x08\x12\x11\n\tkinematic\x18\x06 \x01(\x08\x12\x0f\n\x07\x65nabled\x18\x07 \x01(\x08\x12!\n\x07\x64\x65nsity\x18\x08 \x01(\x0b\x32\x10.gz.msgs.Density\x12#\n\x08inertial\x18\t \x01(\x0b\x32\x11.gz.msgs.Inertial\x12\x1b\n\x04pose\x18\n \x01(\x0b\x32\r.gz.msgs.Pose\x12\x1f\n\x06visual\x18\x0b \x03(\x0b\x32\x0f.gz.msgs.Visual\x12%\n\tcollision\x18\x0c \x03(\x0b\x32\x12.gz.msgs.Collision\x12\x1f\n\x06sensor\x18\r \x03(\x0b\x32\x0f.gz.msgs.Sensor\x12%\n\tprojector\x18\x0e \x03(\x0b\x32\x12.gz.msgs.Projector\x12\x11\n\tcanonical\x18\x0f \x01(\x08\x12!\n\x07\x62\x61ttery\x18\x10 \x03(\x0b\x32\x10.gz.msgs.Battery\x12\x1d\n\x05light\x18\x11 \x03(\x0b\x32\x0e.gz.msgs.Light\x12\x32\n\x10particle_emitter\x18\x12 \x03(\x0b\x32\x18.gz.msgs.ParticleEmitterB\x19\n\x0b\x63om.gz.msgsB\nLinkProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.link_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\nLinkProtos'
  _globals['_LINK']._serialized_start=291
  _globals['_LINK']._serialized_end=813
# @@protoc_insertion_point(module_scope)
