# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/log_status.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/log_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/log_status.proto\x12\x07gz.msgs\x1a\x12gz/msgs/time.proto\x1a\x14gz/msgs/header.proto\"\xd3\x02\n\tLogStatus\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1f\n\x08sim_time\x18\x02 \x01(\x0b\x32\r.gz.msgs.Time\x12,\n\x08log_file\x18\x03 \x01(\x0b\x32\x1a.gz.msgs.LogStatus.LogFile\x1a\xd5\x01\n\x07LogFile\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x11\n\tbase_path\x18\x02 \x01(\t\x12\x11\n\tfull_path\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x02\x12\x34\n\nsize_units\x18\x05 \x01(\x0e\x32 .gz.msgs.LogStatus.LogFile.Units\x12\x18\n\x10record_resources\x18\x06 \x01(\x08\"9\n\x05Units\x12\t\n\x05\x42YTES\x10\x00\x12\x0b\n\x07K_BYTES\x10\x01\x12\x0b\n\x07M_BYTES\x10\x02\x12\x0b\n\x07G_BYTES\x10\x03\x42\x1e\n\x0b\x63om.gz.msgsB\x0fLogStatusProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.log_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017LogStatusProtos'
  _globals['_LOGSTATUS']._serialized_start=80
  _globals['_LOGSTATUS']._serialized_end=419
  _globals['_LOGSTATUS_LOGFILE']._serialized_start=206
  _globals['_LOGSTATUS_LOGFILE']._serialized_end=419
  _globals['_LOGSTATUS_LOGFILE_UNITS']._serialized_start=362
  _globals['_LOGSTATUS_LOGFILE_UNITS']._serialized_end=419
# @@protoc_insertion_point(module_scope)
