# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/marker.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/marker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import material_pb2 as gz_dot_msgs_dot_material__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gz/msgs/marker.proto\x12\x07gz.msgs\x1a\x12gz/msgs/time.proto\x1a\x12gz/msgs/pose.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x16gz/msgs/material.proto\x1a\x14gz/msgs/header.proto\"\xf3\x05\n\x06Marker\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12&\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x16.gz.msgs.Marker.Action\x12\n\n\x02ns\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x04\x12\r\n\x05layer\x18\x05 \x01(\x05\x12\"\n\x04type\x18\x06 \x01(\x0e\x32\x14.gz.msgs.Marker.Type\x12\x1f\n\x08lifetime\x18\x07 \x01(\x0b\x32\r.gz.msgs.Time\x12\x1b\n\x04pose\x18\x08 \x01(\x0b\x32\r.gz.msgs.Pose\x12 \n\x05scale\x18\t \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12#\n\x08material\x18\n \x01(\x0b\x32\x11.gz.msgs.Material\x12 \n\x05point\x18\x0b \x03(\x0b\x32\x11.gz.msgs.Vector3d\x12\x0c\n\x04text\x18\x0c \x01(\t\x12\x0e\n\x06parent\x18\r \x01(\t\x12.\n\nvisibility\x18\x0e \x01(\x0e\x32\x1a.gz.msgs.Marker.Visibility\x12$\n\tmaterials\x18\x0f \x03(\x0b\x32\x11.gz.msgs.Material\"\xdc\x01\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x42OX\x10\x01\x12\x0c\n\x08\x43YLINDER\x10\x02\x12\r\n\tLINE_LIST\x10\x04\x12\x0e\n\nLINE_STRIP\x10\x03\x12\n\n\x06POINTS\x10\x05\x12\n\n\x06SPHERE\x10\x06\x12\x08\n\x04TEXT\x10\x07\x12\x10\n\x0cTRIANGLE_FAN\x10\x08\x12\x11\n\rTRIANGLE_LIST\x10\t\x12\x12\n\x0eTRIANGLE_STRIP\x10\n\x12\x08\n\x04\x43ONE\x10\x0b\x12\t\n\x05\x41RROW\x10\x0c\x12\x08\n\x04\x41XIS\x10\r\x12\x0b\n\x07\x43\x41PSULE\x10\x0e\x12\r\n\tELLIPSOID\x10\x0f\"\x1e\n\nVisibility\x12\x07\n\x03GUI\x10\x00\x12\x07\n\x03\x41LL\x10\x01\";\n\x06\x41\x63tion\x12\x0e\n\nADD_MODIFY\x10\x00\x12\x11\n\rDELETE_MARKER\x10\x01\x12\x0e\n\nDELETE_ALL\x10\x02\x42\x1b\n\x0b\x63om.gz.msgsB\x0cMarkerProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.marker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014MarkerProtos'
  _globals['_MARKER']._serialized_start=144
  _globals['_MARKER']._serialized_end=899
  _globals['_MARKER_TYPE']._serialized_start=586
  _globals['_MARKER_TYPE']._serialized_end=806
  _globals['_MARKER_VISIBILITY']._serialized_start=808
  _globals['_MARKER_VISIBILITY']._serialized_end=838
  _globals['_MARKER_ACTION']._serialized_start=840
  _globals['_MARKER_ACTION']._serialized_end=899
# @@protoc_insertion_point(module_scope)
