# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/material_color.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/material_color.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/material_color.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/entity.proto\x1a\x14gz/msgs/header.proto\"\xc7\x02\n\rMaterialColor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1f\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12\x1f\n\x07\x61mbient\x18\x03 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x1f\n\x07\x64iffuse\x18\x04 \x01(\x0b\x32\x0e.gz.msgs.Color\x12 \n\x08specular\x18\x05 \x01(\x0b\x32\x0e.gz.msgs.Color\x12 \n\x08\x65missive\x18\x06 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x11\n\tshininess\x18\x07 \x01(\x01\x12\x38\n\x0c\x65ntity_match\x18\x08 \x01(\x0e\x32\".gz.msgs.MaterialColor.EntityMatch\"!\n\x0b\x45ntityMatch\x12\t\n\x05\x46IRST\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x42\"\n\x0b\x63om.gz.msgsB\x13MaterialColorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.material_color_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023MaterialColorProtos'
  _globals['_MATERIALCOLOR']._serialized_start=107
  _globals['_MATERIALCOLOR']._serialized_end=434
  _globals['_MATERIALCOLOR_ENTITYMATCH']._serialized_start=401
  _globals['_MATERIALCOLOR_ENTITYMATCH']._serialized_end=434
# @@protoc_insertion_point(module_scope)
