# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/material.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/material.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/material.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/header.proto\"\xc8\x07\n\x08Material\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12(\n\x06script\x18\x02 \x01(\x0b\x32\x18.gz.msgs.Material.Script\x12\x31\n\x0bshader_type\x18\x03 \x01(\x0e\x32\x1c.gz.msgs.Material.ShaderType\x12\x12\n\nnormal_map\x18\x04 \x01(\t\x12\x1f\n\x07\x61mbient\x18\x05 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x1f\n\x07\x64iffuse\x18\x06 \x01(\x0b\x32\x0e.gz.msgs.Color\x12 \n\x08specular\x18\x07 \x01(\x0b\x32\x0e.gz.msgs.Color\x12 \n\x08\x65missive\x18\x08 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x10\n\x08lighting\x18\t \x01(\x08\x12\"\n\x03pbr\x18\n \x01(\x0b\x32\x15.gz.msgs.Material.PBR\x12\x14\n\x0crender_order\x18\x0b \x01(\x01\x12\x14\n\x0c\x64ouble_sided\x18\x0c \x01(\x08\x12\x11\n\tshininess\x18\r \x01(\x01\x1a#\n\x06Script\x12\x0b\n\x03uri\x18\x01 \x03(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a\xa9\x03\n\x03PBR\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".gz.msgs.Material.PBR.WorkflowType\x12\x12\n\nalbedo_map\x18\x02 \x01(\t\x12\x12\n\nnormal_map\x18\x03 \x01(\t\x12\x11\n\tmetalness\x18\x04 \x01(\x01\x12\x15\n\rmetalness_map\x18\x05 \x01(\t\x12\x11\n\troughness\x18\x06 \x01(\x01\x12\x15\n\rroughness_map\x18\x07 \x01(\t\x12\x12\n\nglossiness\x18\x08 \x01(\x01\x12\x16\n\x0eglossiness_map\x18\t \x01(\t\x12\x14\n\x0cspecular_map\x18\n \x01(\t\x12\x17\n\x0f\x65nvironment_map\x18\x0b \x01(\t\x12\x1d\n\x15\x61mbient_occlusion_map\x18\x0c \x01(\t\x12\x14\n\x0c\x65missive_map\x18\r \x01(\t\x12\x11\n\tlight_map\x18\x0e \x01(\t\x12\x1e\n\x16light_map_texcoord_set\x18\x0f \x01(\r\"1\n\x0cWorkflowType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05METAL\x10\x01\x12\x0c\n\x08SPECULAR\x10\x02\"^\n\nShaderType\x12\n\n\x06VERTEX\x10\x00\x12\t\n\x05PIXEL\x10\x01\x12\x1b\n\x17NORMAL_MAP_OBJECT_SPACE\x10\x02\x12\x1c\n\x18NORMAL_MAP_TANGENT_SPACE\x10\x03\x42\x1d\n\x0b\x63om.gz.msgsB\x0eMaterialProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.material_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\016MaterialProtos'
  _globals['_MATERIAL']._serialized_start=79
  _globals['_MATERIAL']._serialized_end=1047
  _globals['_MATERIAL_SCRIPT']._serialized_start=488
  _globals['_MATERIAL_SCRIPT']._serialized_end=523
  _globals['_MATERIAL_PBR']._serialized_start=526
  _globals['_MATERIAL_PBR']._serialized_end=951
  _globals['_MATERIAL_PBR_WORKFLOWTYPE']._serialized_start=902
  _globals['_MATERIAL_PBR_WORKFLOWTYPE']._serialized_end=951
  _globals['_MATERIAL_SHADERTYPE']._serialized_start=953
  _globals['_MATERIAL_SHADERTYPE']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
