# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/model_configuration.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/model_configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!gz/msgs/model_configuration.proto\x12\x07gz.msgs\x1a\x12gz/msgs/time.proto\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/header.proto\"\xb0\x01\n\x12ModelConfiguration\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1b\n\x04time\x18\x02 \x01(\x0b\x32\r.gz.msgs.Time\x12\x13\n\x0bjoint_names\x18\x03 \x03(\t\x12\x17\n\x0fjoint_positions\x18\x04 \x03(\x01\x12\x1b\n\x04pose\x18\x05 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x11\n\tlink_name\x18\x06 \x01(\tB\'\n\x0b\x63om.gz.msgsB\x18ModelConfigurationProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.model_configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\030ModelConfigurationProtos'
  _globals['_MODELCONFIGURATION']._serialized_start=109
  _globals['_MODELCONFIGURATION']._serialized_end=285
# @@protoc_insertion_point(module_scope)
