# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/model.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import axis_aligned_box_pb2 as gz_dot_msgs_dot_axis__aligned__box__pb2
from gz.msgs import joint_pb2 as gz_dot_msgs_dot_joint__pb2
from gz.msgs import link_pb2 as gz_dot_msgs_dot_link__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import visual_pb2 as gz_dot_msgs_dot_visual__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/model.proto\x12\x07gz.msgs\x1a\x1egz/msgs/axis_aligned_box.proto\x1a\x13gz/msgs/joint.proto\x1a\x12gz/msgs/link.proto\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/visual.proto\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xe6\x02\n\x05Model\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x11\n\tis_static\x18\x04 \x01(\x08\x12\x1b\n\x04pose\x18\x05 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x1d\n\x05joint\x18\x06 \x03(\x0b\x32\x0e.gz.msgs.Joint\x12\x1b\n\x04link\x18\x07 \x03(\x0b\x32\r.gz.msgs.Link\x12\x0f\n\x07\x64\x65leted\x18\x08 \x01(\x08\x12\x1f\n\x06visual\x18\t \x03(\x0b\x32\x0f.gz.msgs.Visual\x12 \n\x05scale\x18\n \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x14\n\x0cself_collide\x18\x0b \x01(\x08\x12\x1d\n\x05model\x18\x0c \x03(\x0b\x32\x0e.gz.msgs.Model\x12-\n\x0c\x62ounding_box\x18\r \x01(\x0b\x32\x17.gz.msgs.AxisAlignedBoxB\x1a\n\x0b\x63om.gz.msgsB\x0bModelProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013ModelProtos'
  _globals['_MODEL']._serialized_start=194
  _globals['_MODEL']._serialized_end=552
# @@protoc_insertion_point(module_scope)
