# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/navsat_sensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/navsat_sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import sensor_noise_pb2 as gz_dot_msgs_dot_sensor__noise__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/navsat_sensor.proto\x12\x07gz.msgs\x1a\x1agz/msgs/sensor_noise.proto\x1a\x14gz/msgs/header.proto\"\xfa\x01\n\x0cNavSatSensor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12/\n\x08position\x18\x02 \x01(\x0b\x32\x1d.gz.msgs.NavSatSensor.Sensing\x12/\n\x08velocity\x18\x03 \x01(\x0b\x32\x1d.gz.msgs.NavSatSensor.Sensing\x1ag\n\x07Sensing\x12.\n\x10horizontal_noise\x18\x01 \x01(\x0b\x32\x14.gz.msgs.SensorNoise\x12,\n\x0evertical_noise\x18\x02 \x01(\x0b\x32\x14.gz.msgs.SensorNoiseB!\n\x0b\x63om.gz.msgsB\x12NavSatSensorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.navsat_sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022NavSatSensorProtos'
  _globals['_NAVSATSENSOR']._serialized_start=91
  _globals['_NAVSATSENSOR']._serialized_end=341
  _globals['_NAVSATSENSOR_SENSING']._serialized_start=238
  _globals['_NAVSATSENSOR_SENSING']._serialized_end=341
# @@protoc_insertion_point(module_scope)
