# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/navsat_with_covariance.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/navsat_with_covariance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import float_v_pb2 as gz_dot_msgs_dot_float__v__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gz/msgs/navsat_with_covariance.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x15gz/msgs/float_v.proto\"\xee\x02\n\x14NavSatWithCovariance\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x14\n\x0clatitude_deg\x18\x02 \x01(\x01\x12\x15\n\rlongitude_deg\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12-\n\x13position_covariance\x18\x05 \x01(\x0b\x32\x10.gz.msgs.Float_V\x12 \n\x18position_covariance_type\x18\x06 \x01(\r\x12\x15\n\rvelocity_east\x18\x07 \x01(\x01\x12\x16\n\x0evelocity_north\x18\x08 \x01(\x01\x12\x13\n\x0bvelocity_up\x18\t \x01(\x01\x12-\n\x13velocity_covariance\x18\n \x01(\x0b\x32\x10.gz.msgs.Float_V\x12 \n\x18velocity_covariance_type\x18\x0b \x01(\r\x12\x10\n\x08\x66rame_id\x18\x0c \x01(\tB)\n\x0b\x63om.gz.msgsB\x1aNavSatWithCovarianceProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.navsat_with_covariance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\032NavSatWithCovarianceProtos'
  _globals['_NAVSATWITHCOVARIANCE']._serialized_start=95
  _globals['_NAVSATWITHCOVARIANCE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
