# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/occupancy_grid.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/occupancy_grid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/occupancy_grid.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/pose.proto\x1a\x12gz/msgs/time.proto\"\xf8\x01\n\rOccupancyGrid\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x30\n\x04info\x18\x02 \x01(\x0b\x32\".gz.msgs.OccupancyGrid.MapMetaInfo\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x1a\x85\x01\n\x0bMapMetaInfo\x12$\n\rmap_load_time\x18\x01 \x01(\x0b\x32\r.gz.msgs.Time\x12\x12\n\nresolution\x18\x02 \x01(\x01\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x1d\n\x06origin\x18\x05 \x01(\x0b\x32\r.gz.msgs.PoseB\"\n\x0b\x63om.gz.msgsB\x13OccpuancyGridProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.occupancy_grid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023OccpuancyGridProtos'
  _globals['_OCCUPANCYGRID']._serialized_start=104
  _globals['_OCCUPANCYGRID']._serialized_end=352
  _globals['_OCCUPANCYGRID_MAPMETAINFO']._serialized_start=219
  _globals['_OCCUPANCYGRID_MAPMETAINFO']._serialized_end=352
# @@protoc_insertion_point(module_scope)
