# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/odometry.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/odometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import twist_pb2 as gz_dot_msgs_dot_twist__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/odometry.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/pose.proto\x1a\x13gz/msgs/twist.proto\"g\n\x08Odometry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1b\n\x04pose\x18\x02 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x1d\n\x05twist\x18\x03 \x01(\x0b\x32\x0e.gz.msgs.TwistB\x1d\n\x0b\x63om.gz.msgsB\x0eOdometryProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.odometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\016OdometryProtos'
  _globals['_ODOMETRY']._serialized_start=98
  _globals['_ODOMETRY']._serialized_end=201
# @@protoc_insertion_point(module_scope)
