# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/odometry_with_covariance.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/odometry_with_covariance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import pose_with_covariance_pb2 as gz_dot_msgs_dot_pose__with__covariance__pb2
from gz.msgs import twist_with_covariance_pb2 as gz_dot_msgs_dot_twist__with__covariance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&gz/msgs/odometry_with_covariance.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\"gz/msgs/pose_with_covariance.proto\x1a#gz/msgs/twist_with_covariance.proto\"\xb1\x01\n\x16OdometryWithCovariance\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x39\n\x14pose_with_covariance\x18\x02 \x01(\x0b\x32\x1b.gz.msgs.PoseWithCovariance\x12;\n\x15twist_with_covariance\x18\x03 \x01(\x0b\x32\x1c.gz.msgs.TwistWithCovarianceB+\n\x0b\x63om.gz.msgsB\x1cOdometryWithCovarianceProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.odometry_with_covariance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\034OdometryWithCovarianceProtos'
  _globals['_ODOMETRYWITHCOVARIANCE']._serialized_start=147
  _globals['_ODOMETRYWITHCOVARIANCE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
