# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/packet.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import double_v_pb2 as gz_dot_msgs_dot_double__v__pb2
from gz.msgs import clock_pb2 as gz_dot_msgs_dot_clock__pb2
from gz.msgs import cmd_vel2d_pb2 as gz_dot_msgs_dot_cmd__vel2d__pb2
from gz.msgs import image_pb2 as gz_dot_msgs_dot_image__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import pose_v_pb2 as gz_dot_msgs_dot_pose__v__pb2
from gz.msgs import stringmsg_v_pb2 as gz_dot_msgs_dot_stringmsg__v__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import web_request_pb2 as gz_dot_msgs_dot_web__request__pb2
from gz.msgs import world_stats_pb2 as gz_dot_msgs_dot_world__stats__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gz/msgs/packet.proto\x12\x07gz.msgs\x1a\x16gz/msgs/double_v.proto\x1a\x13gz/msgs/clock.proto\x1a\x17gz/msgs/cmd_vel2d.proto\x1a\x13gz/msgs/image.proto\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/pose_v.proto\x1a\x19gz/msgs/stringmsg_v.proto\x1a\x12gz/msgs/time.proto\x1a\x19gz/msgs/web_request.proto\x1a\x19gz/msgs/world_stats.proto\"\xac\x03\n\x06Packet\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12&\n\tcmd_vel2d\x18\x03 \x01(\x0b\x32\x11.gz.msgs.CmdVel2DH\x00\x12\x1f\n\x05image\x18\x04 \x01(\x0b\x32\x0e.gz.msgs.ImageH\x00\x12,\n\x0cstring_msg_v\x18\x05 \x01(\x0b\x32\x14.gz.msgs.StringMsg_VH\x00\x12*\n\x0bweb_request\x18\x06 \x01(\x0b\x32\x13.gz.msgs.WebRequestH\x00\x12\x1d\n\x04pose\x18\x07 \x01(\x0b\x32\r.gz.msgs.PoseH\x00\x12$\n\x07\x64oublev\x18\x08 \x01(\x0b\x32\x11.gz.msgs.Double_VH\x00\x12!\n\x06pose_v\x18\t \x01(\x0b\x32\x0f.gz.msgs.Pose_VH\x00\x12\x1d\n\x04time\x18\n \x01(\x0b\x32\r.gz.msgs.TimeH\x00\x12\x1f\n\x05\x63lock\x18\x0b \x01(\x0b\x32\x0e.gz.msgs.ClockH\x00\x12/\n\x0bworld_stats\x18\x0c \x01(\x0b\x32\x18.gz.msgs.WorldStatisticsH\x00\x42\t\n\x07\x63ontentB\x1b\n\x0b\x63om.gz.msgsB\x0cPacketProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014PacketProtos'
  _globals['_PACKET']._serialized_start=268
  _globals['_PACKET']._serialized_end=696
# @@protoc_insertion_point(module_scope)
