# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/parameter_declarations.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/parameter_declarations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import parameter_declaration_pb2 as gz_dot_msgs_dot_parameter__declaration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gz/msgs/parameter_declarations.proto\x12\x07gz.msgs\x1a#gz/msgs/parameter_declaration.proto\"V\n\x15ParameterDeclarations\x12=\n\x16parameter_declarations\x18\x01 \x03(\x0b\x32\x1d.gz.msgs.ParameterDeclarationB*\n\x0b\x63om.gz.msgsB\x1bParameterDeclarationsProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.parameter_declarations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\033ParameterDeclarationsProtos'
  _globals['_PARAMETERDECLARATIONS']._serialized_start=86
  _globals['_PARAMETERDECLARATIONS']._serialized_end=172
# @@protoc_insertion_point(module_scope)
