# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/param.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import any_pb2 as gz_dot_msgs_dot_any__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/param.proto\x12\x07gz.msgs\x1a\x11gz/msgs/any.proto\x1a\x14gz/msgs/header.proto\"\xb3\x01\n\x05Param\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12*\n\x06params\x18\x02 \x03(\x0b\x32\x1a.gz.msgs.Param.ParamsEntry\x12 \n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x0e.gz.msgs.Param\x1a;\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.gz.msgs.Any:\x02\x38\x01\x42\x1a\n\x0b\x63om.gz.msgsB\x0b\x45mptyProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013EmptyProtos'
  _globals['_PARAM_PARAMSENTRY']._loaded_options = None
  _globals['_PARAM_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_PARAM']._serialized_start=74
  _globals['_PARAM']._serialized_end=253
  _globals['_PARAM_PARAMSENTRY']._serialized_start=194
  _globals['_PARAM_PARAMSENTRY']._serialized_end=253
# @@protoc_insertion_point(module_scope)
