# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/particle_emitter.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/particle_emitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import boolean_pb2 as gz_dot_msgs_dot_boolean__pb2
from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import float_pb2 as gz_dot_msgs_dot_float__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import material_pb2 as gz_dot_msgs_dot_material__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import stringmsg_pb2 as gz_dot_msgs_dot_stringmsg__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egz/msgs/particle_emitter.proto\x12\x07gz.msgs\x1a\x15gz/msgs/boolean.proto\x1a\x13gz/msgs/color.proto\x1a\x13gz/msgs/float.proto\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/material.proto\x1a\x12gz/msgs/pose.proto\x1a\x17gz/msgs/stringmsg.proto\x1a\x16gz/msgs/vector3d.proto\"\x8d\x06\n\x0fParticleEmitter\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x32\n\x04type\x18\x04 \x01(\x0e\x32$.gz.msgs.ParticleEmitter.EmitterType\x12\x1b\n\x04pose\x18\x05 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x1f\n\x04size\x18\x06 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x1c\n\x04rate\x18\x07 \x01(\x0b\x32\x0e.gz.msgs.Float\x12 \n\x08\x64uration\x18\x08 \x01(\x0b\x32\x0e.gz.msgs.Float\x12\"\n\x08\x65mitting\x18\t \x01(\x0b\x32\x10.gz.msgs.Boolean\x12(\n\rparticle_size\x18\n \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12 \n\x08lifetime\x18\x0b \x01(\x0b\x32\x0e.gz.msgs.Float\x12#\n\x08material\x18\x0c \x01(\x0b\x32\x11.gz.msgs.Material\x12$\n\x0cmin_velocity\x18\r \x01(\x0b\x32\x0e.gz.msgs.Float\x12$\n\x0cmax_velocity\x18\x0e \x01(\x0b\x32\x0e.gz.msgs.Float\x12#\n\x0b\x63olor_start\x18\x0f \x01(\x0b\x32\x0e.gz.msgs.Color\x12!\n\tcolor_end\x18\x10 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\"\n\nscale_rate\x18\x11 \x01(\x0b\x32\x0e.gz.msgs.Float\x12-\n\x11\x63olor_range_image\x18\x12 \x01(\x0b\x32\x12.gz.msgs.StringMsg\x12!\n\x05topic\x18\x13 \x01(\x0b\x32\x12.gz.msgs.StringMsg\x12.\n\x16particle_scatter_ratio\x18\x14 \x01(\x0b\x32\x0e.gz.msgs.Float\">\n\x0b\x45mitterType\x12\t\n\x05POINT\x10\x00\x12\x07\n\x03\x42OX\x10\x01\x12\x0c\n\x08\x43YLINDER\x10\x02\x12\r\n\tELLIPSOID\x10\x03\x42$\n\x0b\x63om.gz.msgsB\x15ParticleEmitterProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.particle_emitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\025ParticleEmitterProtos'
  _globals['_PARTICLEEMITTER']._serialized_start=224
  _globals['_PARTICLEEMITTER']._serialized_end=1005
  _globals['_PARTICLEEMITTER_EMITTERTYPE']._serialized_start=943
  _globals['_PARTICLEEMITTER_EMITTERTYPE']._serialized_end=1005
# @@protoc_insertion_point(module_scope)
