# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/performance_sensor_metrics.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/performance_sensor_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import double_pb2 as gz_dot_msgs_dot_double__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(gz/msgs/performance_sensor_metrics.proto\x12\x07gz.msgs\x1a\x14gz/msgs/double.proto\"\x9f\x01\n\x18PerformanceSensorMetrics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10real_update_rate\x18\x02 \x01(\x01\x12\x17\n\x0fsim_update_rate\x18\x03 \x01(\x01\x12\x1b\n\x13nominal_update_rate\x18\x04 \x01(\x01\x12%\n\x0c\x66ps_optional\x18\x05 \x01(\x0b\x32\x0f.gz.msgs.Doubleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.performance_sensor_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERFORMANCESENSORMETRICS']._serialized_start=76
  _globals['_PERFORMANCESENSORMETRICS']._serialized_end=235
# @@protoc_insertion_point(module_scope)
