# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/physics.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/physics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gz/msgs/physics.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\x8b\x04\n\x07Physics\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.gz.msgs.Physics.Type\x12\x13\n\x0bsolver_type\x18\x03 \x01(\t\x12\x15\n\rmin_step_size\x18\x04 \x01(\x01\x12\x14\n\x0cprecon_iters\x18\x05 \x01(\x05\x12\r\n\x05iters\x18\x06 \x01(\x05\x12\x0b\n\x03sor\x18\x07 \x01(\x01\x12\x0b\n\x03\x63\x66m\x18\x08 \x01(\x01\x12\x0b\n\x03\x65rp\x18\t \x01(\x01\x12\"\n\x1a\x63ontact_max_correcting_vel\x18\n \x01(\x01\x12\x1d\n\x15\x63ontact_surface_layer\x18\x0b \x01(\x01\x12\"\n\x07gravity\x18\x0c \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x16\n\x0e\x65nable_physics\x18\r \x01(\x08\x12\x18\n\x10real_time_factor\x18\x0e \x01(\x01\x12\x1d\n\x15real_time_update_rate\x18\x0f \x01(\x01\x12\x15\n\rmax_step_size\x18\x10 \x01(\x01\x12\x14\n\x0cprofile_name\x18\x11 \x01(\t\x12)\n\x0emagnetic_field\x18\x12 \x01(\x0b\x32\x11.gz.msgs.Vector3d\"2\n\x04Type\x12\x07\n\x03ODE\x10\x00\x12\n\n\x06\x42ULLET\x10\x01\x12\x0b\n\x07SIMBODY\x10\x02\x12\x08\n\x04\x44\x41RT\x10\x03\x42\x1c\n\x0b\x63om.gz.msgsB\rPhysicsProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.physics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\rPhysicsProtos'
  _globals['_PHYSICS']._serialized_start=81
  _globals['_PHYSICS']._serialized_end=604
  _globals['_PHYSICS_TYPE']._serialized_start=554
  _globals['_PHYSICS_TYPE']._serialized_end=604
# @@protoc_insertion_point(module_scope)
