# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/pid.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/pid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import double_pb2 as gz_dot_msgs_dot_double__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/pid.proto\x12\x07gz.msgs\x1a\x14gz/msgs/double.proto\x1a\x14gz/msgs/header.proto\"\xc9\x02\n\x03PID\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12(\n\x0ftarget_optional\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0fp_gain_optional\x18\x03 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0fi_gain_optional\x18\x04 \x01(\x0b\x32\x0f.gz.msgs.Double\x12(\n\x0f\x64_gain_optional\x18\x05 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0ei_max_optional\x18\x06 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0ei_min_optional\x18\x07 \x01(\x0b\x32\x0f.gz.msgs.Double\x12\'\n\x0elimit_optional\x18\x08 \x01(\x0b\x32\x0f.gz.msgs.DoubleB\x18\n\x0b\x63om.gz.msgsB\tPIDProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.pid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\tPIDProtos'
  _globals['_PID']._serialized_start=75
  _globals['_PID']._serialized_end=404
# @@protoc_insertion_point(module_scope)
