# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/pointcloud_packed.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/pointcloud_packed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgz/msgs/pointcloud_packed.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xba\x03\n\x10PointCloudPacked\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12.\n\x05\x66ield\x18\x02 \x03(\x0b\x32\x1f.gz.msgs.PointCloudPacked.Field\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\r\n\x05width\x18\x04 \x01(\r\x12\x14\n\x0cis_bigendian\x18\x05 \x01(\x08\x12\x12\n\npoint_step\x18\x06 \x01(\r\x12\x10\n\x08row_step\x18\x07 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x08 \x01(\x0c\x12\x10\n\x08is_dense\x18\t \x01(\x08\x1a\xd9\x01\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12:\n\x08\x64\x61tatype\x18\x03 \x01(\x0e\x32(.gz.msgs.PointCloudPacked.Field.DataType\x12\r\n\x05\x63ount\x18\x04 \x01(\r\"g\n\x08\x44\x61taType\x12\x08\n\x04INT8\x10\x00\x12\t\n\x05UINT8\x10\x01\x12\t\n\x05INT16\x10\x02\x12\n\n\x06UINT16\x10\x03\x12\t\n\x05INT32\x10\x04\x12\n\n\x06UINT32\x10\x05\x12\x0b\n\x07\x46LOAT32\x10\x06\x12\x0b\n\x07\x46LOAT64\x10\x07\x42%\n\x0b\x63om.gz.msgsB\x16PointCloudPackedProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.pointcloud_packed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\026PointCloudPackedProtos'
  _globals['_POINTCLOUDPACKED']._serialized_start=67
  _globals['_POINTCLOUDPACKED']._serialized_end=509
  _globals['_POINTCLOUDPACKED_FIELD']._serialized_start=292
  _globals['_POINTCLOUDPACKED_FIELD']._serialized_end=509
  _globals['_POINTCLOUDPACKED_FIELD_DATATYPE']._serialized_start=406
  _globals['_POINTCLOUDPACKED_FIELD_DATATYPE']._serialized_end=509
# @@protoc_insertion_point(module_scope)
