# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/pose_with_covariance.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/pose_with_covariance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import float_v_pb2 as gz_dot_msgs_dot_float__v__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gz/msgs/pose_with_covariance.proto\x12\x07gz.msgs\x1a\x15gz/msgs/float_v.proto\x1a\x12gz/msgs/pose.proto\"W\n\x12PoseWithCovariance\x12\x1b\n\x04pose\x18\x01 \x01(\x0b\x32\r.gz.msgs.Pose\x12$\n\ncovariance\x18\x02 \x01(\x0b\x32\x10.gz.msgs.Float_VB\'\n\x0b\x63om.gz.msgsB\x18PoseWithCovarianceProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.pose_with_covariance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\030PoseWithCovarianceProtos'
  _globals['_POSEWITHCOVARIANCE']._serialized_start=90
  _globals['_POSEWITHCOVARIANCE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
