# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/pose_animation.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/pose_animation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/pose_animation.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x12gz/msgs/time.proto\"o\n\rPoseAnimation\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\r\x12\x1b\n\x04pose\x18\x03 \x03(\x0b\x32\r.gz.msgs.Pose\x12\x1b\n\x04time\x18\x04 \x03(\x0b\x32\r.gz.msgs.TimeB\"\n\x0b\x63om.gz.msgsB\x13PoseAnimationProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.pose_animation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023PoseAnimationProtos'
  _globals['_POSEANIMATION']._serialized_start=81
  _globals['_POSEANIMATION']._serialized_end=192
# @@protoc_insertion_point(module_scope)
