# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/projector.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/projector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gz/msgs/projector.proto\x12\x07gz.msgs\x1a\x12gz/msgs/pose.proto\x1a\x14gz/msgs/header.proto\"\xd1\x01\n\tProjector\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07texture\x18\x03 \x01(\t\x12\x1b\n\x04pose\x18\x04 \x01(\x0b\x32\r.gz.msgs.Pose\x12\x0b\n\x03\x66ov\x18\x05 \x01(\x01\x12\x11\n\tnear_clip\x18\x06 \x01(\x01\x12\x10\n\x08\x66\x61r_clip\x18\x07 \x01(\x01\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x12\n\n\x02id\x18\t \x01(\r\x12\x18\n\x10visibility_flags\x18\n \x01(\rB\x1e\n\x0b\x63om.gz.msgsB\x0fProjectorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.projector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017ProjectorProtos'
  _globals['_PROJECTOR']._serialized_start=79
  _globals['_PROJECTOR']._serialized_end=288
# @@protoc_insertion_point(module_scope)
