# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/rest_response.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/rest_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/rest_response.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xa7\x01\n\x0cRestResponse\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12(\n\x04type\x18\x03 \x01(\x0e\x32\x1a.gz.msgs.RestResponse.Type\x12\x0b\n\x03msg\x18\x04 \x01(\t\"3\n\x04Type\x12\x0b\n\x07SUCCESS\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x12\t\n\x05LOGIN\x10\x02\x12\n\n\x06LOGOUT\x10\x03\x42!\n\x0b\x63om.gz.msgsB\x12RestResponseProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.rest_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022RestResponseProtos'
  _globals['_RESTRESPONSE']._serialized_start=63
  _globals['_RESTRESPONSE']._serialized_end=230
  _globals['_RESTRESPONSE_TYPE']._serialized_start=179
  _globals['_RESTRESPONSE_TYPE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
