# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/scene.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/scene.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import fog_pb2 as gz_dot_msgs_dot_fog__pb2
from gz.msgs import sky_pb2 as gz_dot_msgs_dot_sky__pb2
from gz.msgs import light_pb2 as gz_dot_msgs_dot_light__pb2
from gz.msgs import joint_pb2 as gz_dot_msgs_dot_joint__pb2
from gz.msgs import material_pb2 as gz_dot_msgs_dot_material__pb2
from gz.msgs import model_pb2 as gz_dot_msgs_dot_model__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gz/msgs/scene.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x11gz/msgs/fog.proto\x1a\x11gz/msgs/sky.proto\x1a\x13gz/msgs/light.proto\x1a\x13gz/msgs/joint.proto\x1a\x16gz/msgs/material.proto\x1a\x13gz/msgs/model.proto\x1a\x14gz/msgs/header.proto\"\x85\x03\n\x05Scene\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1f\n\x07\x61mbient\x18\x03 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\"\n\nbackground\x18\x04 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x19\n\x03sky\x18\x05 \x01(\x0b\x32\x0c.gz.msgs.Sky\x12\x0f\n\x07shadows\x18\x06 \x01(\x08\x12\x19\n\x03\x66og\x18\x07 \x01(\x0b\x32\x0c.gz.msgs.Fog\x12\x0c\n\x04grid\x18\x08 \x01(\x08\x12\x1d\n\x05model\x18\t \x03(\x0b\x32\x0e.gz.msgs.Model\x12\x1d\n\x05light\x18\n \x03(\x0b\x32\x0e.gz.msgs.Light\x12\x1d\n\x05joint\x18\x0b \x03(\x0b\x32\x0e.gz.msgs.Joint\x12\x15\n\rorigin_visual\x18\x0c \x01(\x08\x12?\n\x1dshadow_caster_material_script\x18\r \x01(\x0b\x32\x18.gz.msgs.Material.ScriptB\x1a\n\x0b\x63om.gz.msgsB\x0bSceneProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.scene_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\013SceneProtos'
  _globals['_SCENE']._serialized_start=201
  _globals['_SCENE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
