# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/sdf_generator_config.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/sdf_generator_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import boolean_pb2 as gz_dot_msgs_dot_boolean__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gz/msgs/sdf_generator_config.proto\x12\x07gz.msgs\x1a\x15gz/msgs/boolean.proto\x1a\x14gz/msgs/header.proto\"\xbc\x04\n\x12SdfGeneratorConfig\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12S\n\x18global_entity_gen_config\x18\x02 \x01(\x0b\x32\x31.gz.msgs.SdfGeneratorConfig.EntityGeneratorConfig\x12^\n\x1boverride_entity_gen_configs\x18\x03 \x03(\x0b\x32\x39.gz.msgs.SdfGeneratorConfig.OverrideEntityGenConfigsEntry\x1a\xdb\x01\n\x15\x45ntityGeneratorConfig\x12-\n\x13\x65xpand_include_tags\x18\x01 \x01(\x0b\x32\x10.gz.msgs.Boolean\x12+\n\x11save_fuel_version\x18\x02 \x01(\x0b\x32\x10.gz.msgs.Boolean\x12\x36\n\x1cresources_use_absolute_paths\x18\x03 \x01(\x0b\x32\x10.gz.msgs.Boolean\x12.\n\x14\x63opy_model_resources\x18\x04 \x01(\x0b\x32\x10.gz.msgs.Boolean\x1ar\n\x1dOverrideEntityGenConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12@\n\x05value\x18\x02 \x01(\x0b\x32\x31.gz.msgs.SdfGeneratorConfig.EntityGeneratorConfig:\x02\x38\x01\x42\'\n\x0b\x63om.gz.msgsB\x18SdfGeneratorConfigProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.sdf_generator_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\030SdfGeneratorConfigProtos'
  _globals['_SDFGENERATORCONFIG_OVERRIDEENTITYGENCONFIGSENTRY']._loaded_options = None
  _globals['_SDFGENERATORCONFIG_OVERRIDEENTITYGENCONFIGSENTRY']._serialized_options = b'8\001'
  _globals['_SDFGENERATORCONFIG']._serialized_start=93
  _globals['_SDFGENERATORCONFIG']._serialized_end=665
  _globals['_SDFGENERATORCONFIG_ENTITYGENERATORCONFIG']._serialized_start=330
  _globals['_SDFGENERATORCONFIG_ENTITYGENERATORCONFIG']._serialized_end=549
  _globals['_SDFGENERATORCONFIG_OVERRIDEENTITYGENCONFIGSENTRY']._serialized_start=551
  _globals['_SDFGENERATORCONFIG_OVERRIDEENTITYGENCONFIGSENTRY']._serialized_end=665
# @@protoc_insertion_point(module_scope)
