# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/sensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import altimeter_sensor_pb2 as gz_dot_msgs_dot_altimeter__sensor__pb2
from gz.msgs import air_speed_sensor_pb2 as gz_dot_msgs_dot_air__speed__sensor__pb2
from gz.msgs import camerasensor_pb2 as gz_dot_msgs_dot_camerasensor__pb2
from gz.msgs import contactsensor_pb2 as gz_dot_msgs_dot_contactsensor__pb2
from gz.msgs import air_pressure_sensor_pb2 as gz_dot_msgs_dot_air__pressure__sensor__pb2
from gz.msgs import gps_sensor_pb2 as gz_dot_msgs_dot_gps__sensor__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import imu_sensor_pb2 as gz_dot_msgs_dot_imu__sensor__pb2
from gz.msgs import lidar_sensor_pb2 as gz_dot_msgs_dot_lidar__sensor__pb2
from gz.msgs import logical_camera_sensor_pb2 as gz_dot_msgs_dot_logical__camera__sensor__pb2
from gz.msgs import magnetometer_sensor_pb2 as gz_dot_msgs_dot_magnetometer__sensor__pb2
from gz.msgs import navsat_sensor_pb2 as gz_dot_msgs_dot_navsat__sensor__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gz/msgs/sensor.proto\x12\x07gz.msgs\x1a\x1egz/msgs/altimeter_sensor.proto\x1a\x1egz/msgs/air_speed_sensor.proto\x1a\x1agz/msgs/camerasensor.proto\x1a\x1bgz/msgs/contactsensor.proto\x1a!gz/msgs/air_pressure_sensor.proto\x1a\x18gz/msgs/gps_sensor.proto\x1a\x14gz/msgs/header.proto\x1a\x18gz/msgs/imu_sensor.proto\x1a\x1agz/msgs/lidar_sensor.proto\x1a#gz/msgs/logical_camera_sensor.proto\x1a!gz/msgs/magnetometer_sensor.proto\x1a\x1bgz/msgs/navsat_sensor.proto\x1a\x12gz/msgs/pose.proto\"\xb1\x05\n\x06Sensor\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x0e\n\x06parent\x18\x04 \x01(\t\x12\x11\n\tparent_id\x18\x05 \x01(\r\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x11\n\talways_on\x18\x07 \x01(\x08\x12\x13\n\x0bupdate_rate\x18\x08 \x01(\x01\x12\x1b\n\x04pose\x18\t \x01(\x0b\x32\r.gz.msgs.Pose\x12%\n\x06\x63\x61mera\x18\n \x01(\x0b\x32\x15.gz.msgs.CameraSensor\x12\'\n\x07\x63ontact\x18\x0b \x01(\x0b\x32\x16.gz.msgs.ContactSensor\x12\x11\n\tvisualize\x18\x0c \x01(\x08\x12\r\n\x05topic\x18\r \x01(\t\x12\x34\n\x0elogical_camera\x18\x0e \x01(\x0b\x32\x1c.gz.msgs.LogicalCameraSensor\x12#\n\x03gps\x18\x0f \x01(\x0b\x32\x12.gz.msgs.GPSSensorB\x02\x18\x01\x12\x1f\n\x03imu\x18\x10 \x01(\x0b\x32\x12.gz.msgs.IMUSensor\x12\x31\n\x0cmagnetometer\x18\x11 \x01(\x0b\x32\x1b.gz.msgs.MagnetometerSensor\x12+\n\taltimeter\x18\x12 \x01(\x0b\x32\x18.gz.msgs.AltimeterSensor\x12\x30\n\x0c\x61ir_pressure\x18\x13 \x01(\x0b\x32\x1a.gz.msgs.AirPressureSensor\x12#\n\x05lidar\x18\x14 \x01(\x0b\x32\x14.gz.msgs.LidarSensor\x12*\n\tair_speed\x18\x15 \x01(\x0b\x32\x17.gz.msgs.AirSpeedSensor\x12%\n\x06navsat\x18\x16 \x01(\x0b\x32\x15.gz.msgs.NavSatSensorB\x1b\n\x0b\x63om.gz.msgsB\x0cSensorProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014SensorProtos'
  _globals['_SENSOR'].fields_by_name['gps']._loaded_options = None
  _globals['_SENSOR'].fields_by_name['gps']._serialized_options = b'\030\001'
  _globals['_SENSOR']._serialized_start=413
  _globals['_SENSOR']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
