# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/serialized.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/serialized.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import world_stats_pb2 as gz_dot_msgs_dot_world__stats__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/serialized.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x19gz/msgs/world_stats.proto\"F\n\x13SerializedComponent\x12\x0c\n\x04type\x18\x01 \x01(\x04\x12\x11\n\tcomponent\x18\x02 \x01(\x0c\x12\x0e\n\x06remove\x18\x03 \x01(\x08\"`\n\x10SerializedEntity\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x30\n\ncomponents\x18\x02 \x03(\x0b\x32\x1c.gz.msgs.SerializedComponent\x12\x0e\n\x06remove\x18\x03 \x01(\x08\"_\n\x0fSerializedState\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12+\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x19.gz.msgs.SerializedEntity\"b\n\x0eSerializedStep\x12\'\n\x05stats\x18\x01 \x01(\x0b\x32\x18.gz.msgs.WorldStatistics\x12\'\n\x05state\x18\x02 \x01(\x0b\x32\x18.gz.msgs.SerializedStateB\r\n\x0b\x63om.gz.msgsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.serialized_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgs'
  _globals['_SERIALIZEDCOMPONENT']._serialized_start=86
  _globals['_SERIALIZEDCOMPONENT']._serialized_end=156
  _globals['_SERIALIZEDENTITY']._serialized_start=158
  _globals['_SERIALIZEDENTITY']._serialized_end=254
  _globals['_SERIALIZEDSTATE']._serialized_start=256
  _globals['_SERIALIZEDSTATE']._serialized_end=351
  _globals['_SERIALIZEDSTEP']._serialized_start=353
  _globals['_SERIALIZEDSTEP']._serialized_end=451
# @@protoc_insertion_point(module_scope)
