# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/serialized_map.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/serialized_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import world_stats_pb2 as gz_dot_msgs_dot_world__stats__pb2
from gz.msgs import serialized_pb2 as gz_dot_msgs_dot_serialized__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/serialized_map.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x19gz/msgs/world_stats.proto\x1a\x18gz/msgs/serialized.proto\"\xc4\x01\n\x13SerializedEntityMap\x12\n\n\x02id\x18\x01 \x01(\x04\x12@\n\ncomponents\x18\x02 \x03(\x0b\x32,.gz.msgs.SerializedEntityMap.ComponentsEntry\x12\x0e\n\x06remove\x18\x03 \x01(\x08\x1aO\n\x0f\x43omponentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.gz.msgs.SerializedComponent:\x02\x38\x01\"\xe9\x01\n\x12SerializedStateMap\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12;\n\x08\x65ntities\x18\x02 \x03(\x0b\x32).gz.msgs.SerializedStateMap.EntitiesEntry\x12&\n\x1ehas_one_time_component_changes\x18\x03 \x01(\x08\x1aM\n\rEntitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.gz.msgs.SerializedEntityMap:\x02\x38\x01\"h\n\x11SerializedStepMap\x12\'\n\x05stats\x18\x01 \x01(\x0b\x32\x18.gz.msgs.WorldStatistics\x12*\n\x05state\x18\x02 \x01(\x0b\x32\x1b.gz.msgs.SerializedStateMapB\r\n\x0b\x63om.gz.msgsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.serialized_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgs'
  _globals['_SERIALIZEDENTITYMAP_COMPONENTSENTRY']._loaded_options = None
  _globals['_SERIALIZEDENTITYMAP_COMPONENTSENTRY']._serialized_options = b'8\001'
  _globals['_SERIALIZEDSTATEMAP_ENTITIESENTRY']._loaded_options = None
  _globals['_SERIALIZEDSTATEMAP_ENTITIESENTRY']._serialized_options = b'8\001'
  _globals['_SERIALIZEDENTITYMAP']._serialized_start=117
  _globals['_SERIALIZEDENTITYMAP']._serialized_end=313
  _globals['_SERIALIZEDENTITYMAP_COMPONENTSENTRY']._serialized_start=234
  _globals['_SERIALIZEDENTITYMAP_COMPONENTSENTRY']._serialized_end=313
  _globals['_SERIALIZEDSTATEMAP']._serialized_start=316
  _globals['_SERIALIZEDSTATEMAP']._serialized_end=549
  _globals['_SERIALIZEDSTATEMAP_ENTITIESENTRY']._serialized_start=472
  _globals['_SERIALIZEDSTATEMAP_ENTITIESENTRY']._serialized_end=549
  _globals['_SERIALIZEDSTEPMAP']._serialized_start=551
  _globals['_SERIALIZEDSTEPMAP']._serialized_end=655
# @@protoc_insertion_point(module_scope)
