# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/server_control.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/server_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgz/msgs/server_control.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\xb9\x01\n\rServerControl\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x17\n\x0fsave_world_name\x18\x02 \x01(\t\x12\x15\n\rsave_filename\x18\x03 \x01(\t\x12\x15\n\ropen_filename\x18\x04 \x01(\t\x12\x11\n\tnew_world\x18\x05 \x01(\x08\x12\x0c\n\x04stop\x18\x06 \x01(\x08\x12\r\n\x05\x63lone\x18\x07 \x01(\x08\x12\x10\n\x08new_port\x18\x08 \x01(\rB\"\n\x0b\x63om.gz.msgsB\x13ServerControlProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.server_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\023ServerControlProtos'
  _globals['_SERVERCONTROL']._serialized_start=64
  _globals['_SERVERCONTROL']._serialized_end=249
# @@protoc_insertion_point(module_scope)
