# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/shadows.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/shadows.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gz/msgs/shadows.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/header.proto\"\xde\x01\n\x07Shadows\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.gz.msgs.Shadows.ShadowType\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.gz.msgs.Color\"h\n\nShadowType\x12\x14\n\x10STENCIL_ADDITIVE\x10\x00\x12\x16\n\x12STENCIL_MODULATIVE\x10\x01\x12\x14\n\x10TEXTURE_ADDITIVE\x10\x02\x12\x16\n\x12TEXTURE_MODULATIVE\x10\x03\x42\x1c\n\x0b\x63om.gz.msgsB\rShadowsProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.shadows_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\rShadowsProtos'
  _globals['_SHADOWS']._serialized_start=78
  _globals['_SHADOWS']._serialized_end=300
  _globals['_SHADOWS_SHADOWTYPE']._serialized_start=196
  _globals['_SHADOWS_SHADOWTYPE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
