# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/sky.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/sky.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import color_pb2 as gz_dot_msgs_dot_color__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gz/msgs/sky.proto\x12\x07gz.msgs\x1a\x13gz/msgs/color.proto\x1a\x14gz/msgs/header.proto\"\xe8\x01\n\x03Sky\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04time\x18\x02 \x01(\x01\x12\x0f\n\x07sunrise\x18\x03 \x01(\x01\x12\x0e\n\x06sunset\x18\x04 \x01(\x01\x12\x12\n\nwind_speed\x18\x05 \x01(\x01\x12\x16\n\x0ewind_direction\x18\x06 \x01(\x01\x12%\n\rcloud_ambient\x18\x07 \x01(\x0b\x32\x0e.gz.msgs.Color\x12\x10\n\x08humidity\x18\x08 \x01(\x01\x12\x17\n\x0fmean_cloud_size\x18\t \x01(\x01\x12\x13\n\x0b\x63ubemap_uri\x18\n \x01(\tB\x18\n\x0b\x63om.gz.msgsB\tSkyProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.sky_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\tSkyProtos'
  _globals['_SKY']._serialized_start=74
  _globals['_SKY']._serialized_end=306
# @@protoc_insertion_point(module_scope)
