# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/spherical_coordinates.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/spherical_coordinates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#gz/msgs/spherical_coordinates.proto\x12\x07gz.msgs\x1a\x14gz/msgs/entity.proto\x1a\x14gz/msgs/header.proto\"\xf0\x02\n\x14SphericalCoordinates\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x41\n\rsurface_model\x18\x02 \x01(\x0e\x32*.gz.msgs.SphericalCoordinates.SurfaceModel\x12\x14\n\x0clatitude_deg\x18\x03 \x01(\x01\x12\x15\n\rlongitude_deg\x18\x04 \x01(\x01\x12\x11\n\televation\x18\x05 \x01(\x01\x12\x13\n\x0bheading_deg\x18\x06 \x01(\x01\x12\x1f\n\x06\x65ntity\x18\x07 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12\x1f\n\x17surface_axis_equatorial\x18\x08 \x01(\x01\x12\x1a\n\x12surface_axis_polar\x18\t \x01(\x01\"A\n\x0cSurfaceModel\x12\x0f\n\x0b\x45\x41RTH_WGS84\x10\x00\x12\x0c\n\x08MOON_SCS\x10\x01\x12\x12\n\x0e\x43USTOM_SURFACE\x10\x02*J\n\x18SphericalCoordinatesType\x12\r\n\tSPHERICAL\x10\x00\x12\x08\n\x04\x45\x43\x45\x46\x10\x01\x12\n\n\x06GLOBAL\x10\x02\x12\t\n\x05LOCAL\x10\x03\x42)\n\x0b\x63om.gz.msgsB\x1aSphericalCoordinatesProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.spherical_coordinates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\032SphericalCoordinatesProtos'
  _globals['_SPHERICALCOORDINATESTYPE']._serialized_start=463
  _globals['_SPHERICALCOORDINATESTYPE']._serialized_end=537
  _globals['_SPHERICALCOORDINATES']._serialized_start=93
  _globals['_SPHERICALCOORDINATES']._serialized_end=461
  _globals['_SPHERICALCOORDINATES_SURFACEMODEL']._serialized_start=396
  _globals['_SPHERICALCOORDINATES_SURFACEMODEL']._serialized_end=461
# @@protoc_insertion_point(module_scope)
