# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/statistic.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/statistic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gz/msgs/statistic.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\x90\x02\n\tStatistic\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.gz.msgs.Statistic.DataType\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\"\x99\x01\n\x08\x44\x61taType\x12\x11\n\rUNINITIALIZED\x10\x00\x12\x0b\n\x07\x41VERAGE\x10\x01\x12\x0b\n\x07MINIMUM\x10\x02\x12\x0b\n\x07MAXIMUM\x10\x03\x12\x0c\n\x08VARIANCE\x10\x04\x12\n\n\x06STDDEV\x10\x05\x12\x10\n\x0cSAMPLE_COUNT\x10\x06\x12\x14\n\x10ROOT_MEAN_SQUARE\x10\x07\x12\x11\n\rMAX_ABS_VALUE\x10\x08\"h\n\x0fStatisticsGroup\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12&\n\nstatistics\x18\x03 \x03(\x0b\x32\x12.gz.msgs.Statistic\"\x94\x01\n\x06Metric\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x33\n\x11statistics_groups\x18\x03 \x03(\x0b\x32\x18.gz.msgs.StatisticsGroup\x12&\n\nstatistics\x18\x04 \x03(\x0b\x32\x12.gz.msgs.StatisticB\x1e\n\x0b\x63om.gz.msgsB\x0fStatisticProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.statistic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017StatisticProtos'
  _globals['_STATISTIC']._serialized_start=59
  _globals['_STATISTIC']._serialized_end=331
  _globals['_STATISTIC_DATATYPE']._serialized_start=178
  _globals['_STATISTIC_DATATYPE']._serialized_end=331
  _globals['_STATISTICSGROUP']._serialized_start=333
  _globals['_STATISTICSGROUP']._serialized_end=437
  _globals['_METRIC']._serialized_start=440
  _globals['_METRIC']._serialized_end=588
# @@protoc_insertion_point(module_scope)
