# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/surface.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/surface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import friction_pb2 as gz_dot_msgs_dot_friction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gz/msgs/surface.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x16gz/msgs/friction.proto\"\xe6\x02\n\x07Surface\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12#\n\x08\x66riction\x18\x02 \x01(\x0b\x32\x11.gz.msgs.Friction\x12\x1f\n\x17restitution_coefficient\x18\x03 \x01(\x01\x12\x18\n\x10\x62ounce_threshold\x18\x04 \x01(\x01\x12\x10\n\x08soft_cfm\x18\x05 \x01(\x01\x12\x10\n\x08soft_erp\x18\x06 \x01(\x01\x12\n\n\x02kp\x18\x07 \x01(\x01\x12\n\n\x02kd\x18\x08 \x01(\x01\x12\x0f\n\x07max_vel\x18\t \x01(\x01\x12\x11\n\tmin_depth\x18\n \x01(\x01\x12\x1f\n\x17\x63ollide_without_contact\x18\x0b \x01(\x08\x12\'\n\x1f\x63ollide_without_contact_bitmask\x18\x0c \x01(\r\x12\x17\n\x0f\x63ollide_bitmask\x18\r \x01(\r\x12\x17\n\x0f\x65lastic_modulus\x18\x0e \x01(\x01\x42\x1c\n\x0b\x63om.gz.msgsB\rSurfaceProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.surface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\rSurfaceProtos'
  _globals['_SURFACE']._serialized_start=81
  _globals['_SURFACE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
