# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/topic_info.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/topic_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import publish_pb2 as gz_dot_msgs_dot_publish__pb2
from gz.msgs import subscribe_pb2 as gz_dot_msgs_dot_subscribe__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gz/msgs/topic_info.proto\x12\x07gz.msgs\x1a\x15gz/msgs/publish.proto\x1a\x17gz/msgs/subscribe.proto\x1a\x14gz/msgs/header.proto\"\x8b\x01\n\tTopicInfo\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x10\n\x08msg_type\x18\x02 \x01(\t\x12#\n\tpublisher\x18\x03 \x03(\x0b\x32\x10.gz.msgs.Publish\x12&\n\nsubscriber\x18\x04 \x03(\x0b\x32\x12.gz.msgs.SubscribeB\x1e\n\x0b\x63om.gz.msgsB\x0fTopicInfoProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.topic_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\017TopicInfoProtos'
  _globals['_TOPICINFO']._serialized_start=108
  _globals['_TOPICINFO']._serialized_end=247
# @@protoc_insertion_point(module_scope)
