# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/track_visual.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/track_visual.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agz/msgs/track_visual.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector3d.proto\x1a\x14gz/msgs/header.proto\"\xe7\x01\n\x0bTrackVisual\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x1b\n\x13inherit_orientation\x18\x04 \x01(\x08\x12\x10\n\x08min_dist\x18\x05 \x01(\x01\x12\x10\n\x08max_dist\x18\x06 \x01(\x01\x12\x0e\n\x06static\x18\x07 \x01(\x08\x12\x17\n\x0fuse_model_frame\x18\x08 \x01(\x08\x12\x1e\n\x03xyz\x18\t \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\x13\n\x0binherit_yaw\x18\n \x01(\x08\x42 \n\x0b\x63om.gz.msgsB\x11TrackVisualProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.track_visual_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\021TrackVisualProtos'
  _globals['_TRACKVISUAL']._serialized_start=86
  _globals['_TRACKVISUAL']._serialized_end=317
# @@protoc_insertion_point(module_scope)
