# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/user_cmd.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/user_cmd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import light_pb2 as gz_dot_msgs_dot_light__pb2
from gz.msgs import model_pb2 as gz_dot_msgs_dot_model__pb2
from gz.msgs import world_control_pb2 as gz_dot_msgs_dot_world__control__pb2
from gz.msgs import wrench_pb2 as gz_dot_msgs_dot_wrench__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gz/msgs/user_cmd.proto\x12\x07gz.msgs\x1a\x13gz/msgs/light.proto\x1a\x13gz/msgs/model.proto\x1a\x1bgz/msgs/world_control.proto\x1a\x14gz/msgs/wrench.proto\x1a\x14gz/msgs/header.proto\"\xd2\x02\n\x07UserCmd\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12#\n\x04type\x18\x04 \x01(\x0e\x32\x15.gz.msgs.UserCmd.Type\x12\x1d\n\x05model\x18\x05 \x03(\x0b\x32\x0e.gz.msgs.Model\x12\x1d\n\x05light\x18\x06 \x03(\x0b\x32\x0e.gz.msgs.Light\x12\x13\n\x0b\x65ntity_name\x18\x07 \x01(\t\x12,\n\rworld_control\x18\x08 \x01(\x0b\x32\x15.gz.msgs.WorldControl\x12\x1f\n\x06wrench\x18\t \x01(\x0b\x32\x0f.gz.msgs.Wrench\">\n\x04Type\x12\n\n\x06MOVING\x10\x00\x12\x11\n\rWORLD_CONTROL\x10\x01\x12\n\n\x06WRENCH\x10\x02\x12\x0b\n\x07SCALING\x10\x03\x42\x1c\n\x0b\x63om.gz.msgsB\rUserCmdProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.user_cmd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\rUserCmdProtos'
  _globals['_USERCMD']._serialized_start=151
  _globals['_USERCMD']._serialized_end=489
  _globals['_USERCMD_TYPE']._serialized_start=427
  _globals['_USERCMD_TYPE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
