# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/version_range.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/version_range.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import version_pb2 as gz_dot_msgs_dot_version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/version_range.proto\x12\x07gz.msgs\x1a\x15gz/msgs/version.proto\"L\n\x0cVersionRange\x12\x1d\n\x03min\x18\x01 \x01(\x0b\x32\x10.gz.msgs.Version\x12\x1d\n\x03max\x18\x02 \x01(\x0b\x32\x10.gz.msgs.VersionB\x1b\n\x0b\x63om.gz.msgsB\x0cVersionRangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.version_range_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014VersionRange'
  _globals['_VERSIONRANGE']._serialized_start=63
  _globals['_VERSIONRANGE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
