# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/visual.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/visual.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import pose_pb2 as gz_dot_msgs_dot_pose__pb2
from gz.msgs import geometry_pb2 as gz_dot_msgs_dot_geometry__pb2
from gz.msgs import material_pb2 as gz_dot_msgs_dot_material__pb2
from gz.msgs import plugin_pb2 as gz_dot_msgs_dot_plugin__pb2
from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14gz/msgs/visual.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/pose.proto\x1a\x16gz/msgs/geometry.proto\x1a\x16gz/msgs/material.proto\x1a\x14gz/msgs/plugin.proto\x1a\x16gz/msgs/vector3d.proto\"\xd2\x04\n\x06Visual\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12\x13\n\x0bparent_name\x18\x04 \x01(\t\x12\x11\n\tparent_id\x18\x05 \x01(\r\x12\x14\n\x0c\x63\x61st_shadows\x18\x06 \x01(\x08\x12\x14\n\x0ctransparency\x18\x07 \x01(\x01\x12\x13\n\x0blaser_retro\x18\x08 \x01(\x01\x12\x1b\n\x04pose\x18\t \x01(\x0b\x32\r.gz.msgs.Pose\x12#\n\x08geometry\x18\n \x01(\x0b\x32\x11.gz.msgs.Geometry\x12#\n\x08material\x18\x0b \x01(\x0b\x32\x11.gz.msgs.Material\x12\x0f\n\x07visible\x18\x0c \x01(\x08\x12\x11\n\tdelete_me\x18\r \x01(\x08\x12\x11\n\tis_static\x18\x0e \x01(\x08\x12\x1f\n\x06plugin\x18\x0f \x03(\x0b\x32\x0f.gz.msgs.Plugin\x12 \n\x05scale\x18\x10 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12\"\n\x04meta\x18\x11 \x01(\x0b\x32\x14.gz.msgs.Visual.Meta\x12\"\n\x04type\x18\x12 \x01(\x0e\x32\x14.gz.msgs.Visual.Type\x1a\x15\n\x04Meta\x12\r\n\x05layer\x18\x01 \x01(\x05\"d\n\x04Type\x12\n\n\x06\x45NTITY\x10\x00\x12\t\n\x05MODEL\x10\x01\x12\x08\n\x04LINK\x10\x02\x12\n\n\x06VISUAL\x10\x03\x12\r\n\tCOLLISION\x10\x04\x12\n\n\x06SENSOR\x10\x05\x12\x07\n\x03GUI\x10\x06\x12\x0b\n\x07PHYSICS\x10\x07\x42\x1b\n\x0b\x63om.gz.msgsB\x0cVisualProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.visual_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\014VisualProtos'
  _globals['_VISUAL']._serialized_start=170
  _globals['_VISUAL']._serialized_end=764
  _globals['_VISUAL_META']._serialized_start=641
  _globals['_VISUAL_META']._serialized_end=662
  _globals['_VISUAL_TYPE']._serialized_start=664
  _globals['_VISUAL_TYPE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
