# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/wheel_slip_parameters_cmd.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/wheel_slip_parameters_cmd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import entity_pb2 as gz_dot_msgs_dot_entity__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'gz/msgs/wheel_slip_parameters_cmd.proto\x12\x07gz.msgs\x1a\x14gz/msgs/entity.proto\x1a\x14gz/msgs/header.proto\"\xda\x01\n\x16WheelSlipParametersCmd\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1f\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x0f.gz.msgs.Entity\x12\x1f\n\x17slip_compliance_lateral\x18\x04 \x01(\x01\x12$\n\x1cslip_compliance_longitudinal\x18\x05 \x01(\x01\x12\x18\n\x10\x66riction_lateral\x18\x06 \x01(\x01\x12\x1d\n\x15\x66riction_longitudinal\x18\x07 \x01(\x01\x42%\n\x0b\x63om.gz.msgsB\x16WheelSlipParametersCmdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.wheel_slip_parameters_cmd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\026WheelSlipParametersCmd'
  _globals['_WHEELSLIPPARAMETERSCMD']._serialized_start=97
  _globals['_WHEELSLIPPARAMETERSCMD']._serialized_end=315
# @@protoc_insertion_point(module_scope)
