# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/world_stats.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/world_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import log_playback_stats_pb2 as gz_dot_msgs_dot_log__playback__stats__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gz/msgs/world_stats.proto\x12\x07gz.msgs\x1a gz/msgs/log_playback_stats.proto\x1a\x12gz/msgs/time.proto\x1a\x14gz/msgs/header.proto\"\xdb\x02\n\x0fWorldStatistics\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x1f\n\x08sim_time\x18\x02 \x01(\x0b\x32\r.gz.msgs.Time\x12!\n\npause_time\x18\x03 \x01(\x0b\x32\r.gz.msgs.Time\x12 \n\treal_time\x18\x04 \x01(\x0b\x32\r.gz.msgs.Time\x12\x0e\n\x06paused\x18\x05 \x01(\x08\x12\x12\n\niterations\x18\x06 \x01(\x04\x12\x13\n\x0bmodel_count\x18\x07 \x01(\x05\x12:\n\x12log_playback_stats\x18\x08 \x01(\x0b\x32\x1e.gz.msgs.LogPlaybackStatistics\x12\x18\n\x10real_time_factor\x18\t \x01(\x01\x12 \n\tstep_size\x18\n \x01(\x0b\x32\r.gz.msgs.Time\x12\x10\n\x08stepping\x18\x0b \x01(\x08\x42\x1f\n\x0b\x63om.gz.msgsB\x10WorldStatsProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.world_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\020WorldStatsProtos'
  _globals['_WORLDSTATISTICS']._serialized_start=115
  _globals['_WORLDSTATISTICS']._serialized_end=462
# @@protoc_insertion_point(module_scope)
