# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/world_control.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/world_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import world_reset_pb2 as gz_dot_msgs_dot_world__reset__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2
from gz.msgs import time_pb2 as gz_dot_msgs_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bgz/msgs/world_control.proto\x12\x07gz.msgs\x1a\x19gz/msgs/world_reset.proto\x1a\x14gz/msgs/header.proto\x1a\x12gz/msgs/time.proto\"\xba\x01\n\x0cWorldControl\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\r\n\x05pause\x18\x02 \x01(\x08\x12\x0c\n\x04step\x18\x03 \x01(\x08\x12\x12\n\nmulti_step\x18\x04 \x01(\r\x12\"\n\x05reset\x18\x05 \x01(\x0b\x32\x13.gz.msgs.WorldReset\x12\x0c\n\x04seed\x18\x06 \x01(\r\x12&\n\x0frun_to_sim_time\x18\x07 \x01(\x0b\x32\r.gz.msgs.TimeB!\n\x0b\x63om.gz.msgsB\x12WorldControlProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.world_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\022WorldControlProtos'
  _globals['_WORLDCONTROL']._serialized_start=110
  _globals['_WORLDCONTROL']._serialized_end=296
# @@protoc_insertion_point(module_scope)
