# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gz/msgs/world_modify.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'gz/msgs/world_modify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agz/msgs/world_modify.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.proto\"\x86\x01\n\x0bWorldModify\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x12\n\nworld_name\x18\x02 \x01(\t\x12\x0e\n\x06remove\x18\x03 \x01(\x08\x12\x0e\n\x06\x63reate\x18\x04 \x01(\x08\x12\x0e\n\x06\x63loned\x18\x05 \x01(\x08\x12\x12\n\ncloned_uri\x18\x06 \x01(\tB \n\x0b\x63om.gz.msgsB\x11WorldModifyProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.world_modify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.gz.msgsB\021WorldModifyProtos'
  _globals['_WORLDMODIFY']._serialized_start=62
  _globals['_WORLDMODIFY']._serialized_end=196
# @@protoc_insertion_point(module_scope)
